/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Avatar.glb -o src/components/Avatar.jsx -k -r public 
*/

import { useAnimations, useFBX, useGLTF, useScroll } from '@react-three/drei';
import { useFrame, useGraph } from '@react-three/fiber';
import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { SkeletonUtils } from 'three-stdlib';

import { useMobile } from '../../../hooks/useMobile';

export function Avatar(props) {
  const { isMobile } = useMobile();
  const { scene } = useGLTF('/models/Avatar.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { animations: idleAnimation } = useFBX('/animations/Idle.fbx');
  const { animations: walkingAnimation } = useFBX('/animations/Walking.fbx');

  const group = useRef();
  idleAnimation[0].name = 'Idle';
  walkingAnimation[0].name = 'Walking';

  const { actions } = useAnimations(
    [idleAnimation[0], walkingAnimation[0]],
    group
  );
  const [currentAnimation, setCurrentAnimation] = useState('Idle');
  const scrollData = useScroll();
  const lastScroll = useRef(0);
  const animationTimeout = useRef(null);

  // Set up animations only once when component mounts
  useEffect(() => {
    // Start with Idle animation
    actions['Idle'].play();
    actions['Walking'].play();

    // Set initial weights
    actions['Idle'].setEffectiveWeight(1);
    actions['Walking'].setEffectiveWeight(0);

    return () => {
      actions['Idle'].stop();
      actions['Walking'].stop();
    };
  }, [actions]);

  useFrame(() => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    const isMoving = Math.abs(scrollDelta) > 0.00001;
    let rotationTarget = 0;

    if (isMoving) {
      clearTimeout(animationTimeout.current);
      rotationTarget =
        scrollDelta > 0
          ? isMobile
            ? Math.PI / 2
            : 0
          : isMobile
          ? -Math.PI / 2
          : Math.PI;

      // Smoothly transition to walking
      actions['Idle'].setEffectiveWeight(0);
      actions['Walking'].setEffectiveWeight(1);

      if (currentAnimation !== 'Walking') {
        setCurrentAnimation('Walking');
      }
    } else if (currentAnimation !== 'Idle') {
      // Add a small delay before transitioning back to idle
      animationTimeout.current = setTimeout(() => {
        // Smoothly transition back to idle
        actions['Walking'].setEffectiveWeight(0);
        actions['Idle'].setEffectiveWeight(1);
        setCurrentAnimation('Idle');
      }, 150); // Small delay to prevent jerky transitions
    }

    // Smooth rotation
    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      rotationTarget,
      0.05
    );
    lastScroll.current = scrollData.offset;
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Glasses"
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload('/models/Avatar.glb');
useFBX.preload('/animations/Idle.fbx');
useFBX.preload('/animations/Walking.fbx');
