/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Grass.glb -o src/components/Grass.jsx -r public 
Author: Digital screen official (https://sketchfab.com/ck212575)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-02-539d1c154c944e24a04478ee32f0a960
Title: Grass 02
*/

import { useGLTF } from '@react-three/drei';

export function Grass(props) {
  const { nodes, materials } = useGLTF('/models/grass.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/grass.glb');
