/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Lamp.glb -o src/components/Lamp.jsx -r public
Lamp by burunduk [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/OQ2HurCvOz)
*/
import { SpotLight, useGLTF } from '@react-three/drei';
import { useRef } from 'react';

import { useMobile } from '../../../hooks/useMobile';

export function Lamp(props) {
  const { nodes, materials } = useGLTF('/models/Lamp.glb');
  const { isMobile } = useMobile();
  const spotLightRef = useRef();
  const spotlightPosition = [0.4, 2.16, 0.0];

  return (
    <group {...props} dispose={null}>
      <group position={[0.326, 0.78, -0.505]} rotation={[-1.419, 0.087, 2.088]}>
        <mesh
          geometry={nodes.Cylinder398_1.geometry}
          material={materials.brown}
        />
        <mesh
          geometry={nodes.Cylinder398_2.geometry}
          material={materials.black}
        />
      </group>
      <group position={[0.44, 2.164, -0.331]} rotation={[0, 0, Math.PI / 6]}>
        <mesh
          geometry={nodes.Cylinder400_1.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.Cylinder400_2.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.Cylinder400_3.geometry}
          material={materials.L_yellow}
        >
          {/* Make the lamp bulb glow */}
          <meshStandardMaterial
            {...materials.L_yellow}
            emissive="#ffff80"
            emissiveIntensity={2}
            toneMapped={false}
          />
        </mesh>
      </group>

      {/* Add spotlight */}
      {!isMobile && (
        <SpotLight
          ref={spotLightRef}
          position={spotlightPosition}
          angle={0.4}
          attenuation={5}
          distance={8}
          intensity={1}
          penumbra={1}
          color="#ffff80"
          castShadow
          target-position={[0.7, -0.7, 0.3]}
        />
      )}
    </group>
  );
}

useGLTF.preload('/models/Lamp.glb');
