import { CheckCircle2 } from "lucide-react";
import type { Project } from "@/types";

export const DEFAULT_FEATURE_ICON = CheckCircle2;

export const PROJECTS: Record<string, Project> = {
  twinAI: {
    id: "twinAI",
    title: "TwinAI - AI-Powered Digital Twins for Therapy",
    description:
      "A platform that uses AI-powered digital twins to revolutionize mental health therapy and treatment.",
    subdesc:
      "TwinAI creates virtual representations of patients’ psychological states, enabling therapists to simulate interventions, track mood patterns, and develop personalized treatment plans.",
    year: "2024",
    client: "Personal Project",
    services: "AI, Web Development",
    location: "Singapore",
    href: "https://twin-ai-one.vercel.app/",
    github: "https://github.com/Benjam11n/TwinAI",
    texture: "/textures/project/project1.mp4",
    logo: "/projects/project1-logo.png",
    logoStyle: {
      backgroundColor: "#151a11",
      border: "0.2px solid #233814",
      boxShadow: "0px 0px 60px 0px #324d1f",
    },
    spotlight: "/assets/spotlight4.png",
    techStack: [
      {
        name: "React",
        colorLight: "#E0F7FA",
        colorDark: "#001b59",
        size: "xl",
        path: "/assets/react.svg",
      },
      {
        name: "Tailwind",
        colorLight: "#E0F2F1",
        colorDark: "#0F766E",
        size: "xl",
        path: "/assets/tailwindcss.png",
      },
      {
        name: "TypeScript",
        colorLight: "#E3F2FD",
        colorDark: "#3178C6",
        size: "xl",
        path: "/assets/typescript.svg",
      },
      {
        name: "MongoDB",
        colorLight: "#E8F5E9",
        colorDark: "#023430",
        size: "lg",
        path: "/assets/mongodb.svg",
      },
      {
        name: "Google Gemini",
        colorLight: "#E3F2FD",
        colorDark: "#0D4C87",
        size: "lg",
        path: "/assets/google-gemini.svg",
      },
      {
        name: "Pytorch",
        colorLight: "#E1F5FE",
        colorDark: "#0D4C87",
        size: "lg",
        path: "/assets/pytorch.svg",
      },
    ],
    features: [
      "Real-time voice-based therapy sessions",
      "Interactive AI patient simulations",
      "Contextual, condition-specific responses",
      "Learning from therapeutic techniques",
      "Voice processing for seamless interaction",
    ],
  },
  quickie: {
    id: "quickie",
    title: "Quickie - AI-Powered Marketplace",
    description:
      "Quickie is an innovative e-commerce platform that leverages AI technology to provide personalized perfume recommendations to users.",
    subdesc:
      "Built as a unique e-commerce app with Next.js 15, Tailwind CSS, TypeScript, Framer Motion, shadcn/ui, Zustand, React Query and MongoDB, Quickie is designed to be beautiful and memorable yet performant.",
    year: "2024",
    client: "Personal Project",
    services: "E-commerce, AI",
    location: "Singapore",
    status: "in-development",
    github: "https://github.com/Benjam11n/Quickie",
    texture: "/textures/project/project2.mp4",
    logo: "/projects/project2-logo.png",
    logoStyle: {
      backgroundColor: "#170040",
      border: "0.2px solid #0f0226",
      boxShadow: "0px 0px 60px 0px #4f248f",
    },
    spotlight: "/assets/spotlight1.png",
    techStack: [
      {
        name: "React",
        colorLight: "#E0F7FA",
        colorDark: "#001b59",
        size: "xl",
        path: "/assets/react.svg",
      },
      {
        name: "Tailwind",
        colorLight: "#E0F2F1",
        colorDark: "#0F766E",
        size: "xl",
        path: "/assets/tailwindcss.png",
      },
      {
        name: "TypeScript",
        colorLight: "#E3F2FD",
        colorDark: "#3178C6",
        size: "xl",
        path: "/assets/typescript.svg",
      },
      {
        name: "Framer Motion",
        colorLight: "#F3E5F5",
        colorDark: "#2e00a1",
        size: "lg",
        path: "/assets/framer.png",
      },
      {
        name: "Zustand",
        colorLight: "#FFF3E0",
        colorDark: "#E67E22",
        size: "lg",
        path: "/assets/zustand.png",
      },
      {
        name: "MongoDB",
        colorLight: "#E8F5E9",
        colorDark: "#023430",
        size: "lg",
        path: "/assets/mongodb.svg",
      },
    ],
    features: [
      "Product search and filtering",
      "AI-powered recommendation system",
      "Waitlist system",
      "User authentication and profiles",
      "Email confirmation and notifications",
    ],
  },
  chip: {
    id: "chip",
    title: "Chip - Play poker anytime, anywhere",
    description:
      "A digital poker chip tracker that lets you and your friends enjoy poker games without physical chips. Perfect for casual games anywhere.",
    subdesc:
      "Built with Next.js, React, TypeScript, Framer motion, TailwindCSS and Supabase, Chip provides a seamless and reliable poker experience with real-time updates and easy chip management.",
    year: "2024",
    client: "Personal Project",
    services: "Web App, Real-time",
    location: "Singapore",
    href: "https://chip-sg.vercel.app/",
    status: "completed",
    github: "https://github.com/Benjam11n/Chip",
    texture: "/textures/project/project3.mp4",
    logo: "/projects/project3-logo.png",
    logoStyle: {
      backgroundColor: "#000000",
      border: "0.2px solid #24020b",
      boxShadow: "0px 0px 60px 0px #380310",
    },
    spotlight: "/assets/spotlight3.png",
    techStack: [
      {
        name: "React",
        colorLight: "#E0F7FA",
        colorDark: "#001b59",
        size: "xl",
        path: "/assets/react.svg",
      },
      {
        name: "Tailwind",
        colorLight: "#E0F2F1",
        colorDark: "#0F766E",
        size: "xl",
        path: "/assets/tailwindcss.png",
      },
      {
        name: "TypeScript",
        colorLight: "#E3F2FD",
        colorDark: "#3178C6",
        size: "xl",
        path: "/assets/typescript.svg",
      },
      {
        name: "Framer Motion",
        colorLight: "#F3E5F5",
        colorDark: "#2e00a1",
        size: "lg",
        path: "/assets/framer.png",
      },
      {
        name: "Supabase",
        colorLight: "#E8F5E9",
        colorDark: "#525252",
        size: "lg",
        path: "/assets/supabase.svg",
      },
    ],
    features: [
      "Real-time chip count tracking",
      "Multiple table support",
      "Customizable starting stacks",
      "Blind timer and level management",
      "Game history and statistics",
    ],
  },
  "birds-of-a-feather": {
    id: "birds-of-a-feather",
    title: "Birds of a Feather - Community Forum",
    description:
      "Birds of a Feather is a community forum designed for bird lovers to connect, share knowledge, and discuss their passion for birds.",
    subdesc:
      "Built with React, Typescript Tailwind CSS, shadcn/ui, React Query and Docker, Birds of a Feather is a modern forum that brings bird enthusiasts together.",
    year: "2024",
    client: "Personal Project",
    services: "Community, Forum",
    location: "Singapore",
    github: "https://github.com/Benjam11n/Birds-of-a-Feather-frontend",
    texture: "/textures/project/project4.mp4",
    logo: "/projects/project4-logo.png",
    logoStyle: {
      backgroundColor: "#16015c",
      border: "0.2px solid #0c0036",
      boxShadow: "0px 0px 60px 0px #2F6DB54D",
    },
    spotlight: "/assets/spotlight2.png",
    techStack: [
      {
        name: "React",
        colorLight: "#E0F7FA",
        colorDark: "#001b59",
        size: "xl",
        path: "/assets/react.svg",
      },
      {
        name: "Tailwind",
        colorLight: "#E0F2F1",
        colorDark: "#0F766E",
        size: "xl",
        path: "/assets/tailwindcss.png",
      },
      {
        name: "TypeScript",
        colorLight: "#E3F2FD",
        colorDark: "#3178C6",
        size: "xl",
        path: "/assets/typescript.svg",
      },
      {
        name: "PostgreSQL",
        colorLight: "#E3F2FD",
        colorDark: "#2F5E8D",
        size: "lg",
        path: "/assets/pgsql.svg",
      },
      {
        name: "Docker",
        colorLight: "#E1F5FE",
        colorDark: "#1D63ED",
        size: "md",
        path: "/assets/docker.svg",
      },
    ],
    features: [
      "Real-time community discussions",
      "Photo and video sharing for bird sightings",
      "Group creation and management",
      "User profiles with bird watching history",
      "Bird species identification assistance",
    ],
  },
  worldquant: {
    id: "worldquant",
    title: "WorldQuant NUS Alphathon - 4th Place Winner",
    description:
      "Achieved 4th place in the prestigious WorldQuant NUS Alphathon by developing and optimizing alpha-generating quantitative trading strategies.",
    subdesc:
      "Utilized Fast Expression Language and quantitative research methodologies to identify market patterns and develop high-performance predictive models on the BRAIN platform.",
    year: "2024",
    client: "WorldQuant",
    services: "Quantitative Research, Alpha Design",
    location: "Singapore",
    texture: "/textures/project/project5.mp4",
    logo: "/projects/project5-logo.png",
    logoStyle: {
      backgroundColor: "#0E1F38",
      border: "0.2px solid #0E2D58",
      boxShadow: "0px 0px 60px 0px #2F67B64D",
    },
    spotlight: "/assets/spotlight4.png",
    techStack: [
      {
        name: "Python",
        colorLight: "#E3F2FD",
        colorDark: "#1E2D3B",
        size: "xl",
        path: "/assets/python.svg",
      },
      {
        name: "Numpy",
        colorLight: "#E1F5FE",
        colorDark: "#013243",
        size: "lg",
        path: "/assets/numpy.svg",
      },
      {
        name: "Pandas",
        colorLight: "#F3E5F5",
        colorDark: "#150458",
        size: "lg",
        path: "/assets/pandas.svg",
      },
    ],
  },
};
