export const STACKS = [
  {
    name: "React",
    icon: "/assets/react.svg",
    category: "Frontend",
    colorLight: "#E0F7FA",
    colorDark: "#001b59",
  },
  {
    name: "Next.js",
    icon: "/assets/nextjs.svg",
    category: "Framework",
    colorLight: "#F3F4F6",
    colorDark: "#3b3b3bff",
  },
  {
    name: "TypeScript",
    icon: "/assets/typescript.svg",
    category: "Language",
    colorLight: "#E3F2FD",
    colorDark: "#00273F",
  },
  {
    name: "Tailwind",
    icon: "/assets/tailwindcss.png",
    category: "Styling",
    colorLight: "#E0F2F1",
    colorDark: "#0B2830",
  },
  {
    name: "Framer",
    icon: "/assets/framer.png",
    category: "Animation",
    colorLight: "#F3E5F5",
    colorDark: "#180036",
  },
  {
    name: "MongoDB",
    icon: "/assets/mongodb.svg",
    category: "Database",
    colorLight: "#E8F5E9",
    colorDark: "#001E0E",
  },
  {
    name: "PostgreSQL",
    icon: "/assets/pgsql.svg",
    category: "Database",
    colorLight: "#E3F2FD",
    colorDark: "#0E1A2B",
  },
  {
    name: "Docker",
    icon: "/assets/docker.svg",
    category: "DevOps",
    colorLight: "#E1F5FE",
    colorDark: "#0D2C4A",
  },
  {
    name: "Node.js",
    icon: "/assets/node.svg",
    category: "Backend",
    colorLight: "#F1F8E9",
    colorDark: "#1f3519ff",
  },
  {
    name: "Python",
    icon: "/assets/python.svg",
    category: "Language",
    colorLight: "#E3F2FD",
    colorDark: "#1E2D3B",
  },
];
