/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/RetroComputer.glb -o src/list/components/RetroComputer.jsx -r public 
Author: creosine (https://sketchfab.com/creosine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-low-poly-game-model-14b057db85944e7681a5d68993348f22
Title: old PC low poly game model
*/

import { useGSAP } from '@gsap/react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import { useEffect } from 'react';
import { useRef } from 'react';
import gsap from 'gsap';

export function RetroComputer({ texture, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/RetroComputer.glb');
  const txt = useVideoTexture(
    texture ? texture : '/textures/project/project1.mp4'
  );

  useEffect(() => {
    if (txt) {
      txt.flipY = false;
    }
  }, [txt]);

  // Enhanced rotation animation
  useGSAP(() => {
    gsap.fromTo(
      group.current.rotation,
      {
        y: -Math.PI / 2, // Start from -90 degrees (side view)
      },
      {
        y: 0, // Rotate to front (0 degrees)
        duration: 1.2,
        ease: 'power2.out', // Smoother easing
        immediateRender: true,
      }
    );
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials['01___Default']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.832, 1, 1]}
          />
          <mesh
            position={[0, 45, 17]}
            rotation={[-0.02, -Math.PI, -Math.PI]} // Tilt the screen slightly
            scale={38}
          >
            <planeGeometry args={[1.4, 1]} />
            <meshBasicMaterial map={txt} side={2} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/RetroComputer.glb');
