/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: julianikonenko (https://sketchfab.com/julianikonenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rick-and-morty-lab-a55ff01c81de409c8b127c5d39460352
Title: rick and morty lab
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    chair_metalic_0: THREE.Mesh;
    Plane006_red_0: THREE.Mesh;
    Plane007_red_0: THREE.Mesh;
    Plane008_metalic_0: THREE.Mesh;
    poster_wood001_0: THREE.Mesh;
    box_wood002_0: THREE.Mesh;
    box001_pink_0: THREE.Mesh;
    washbasin_metalic_0: THREE.Mesh;
    washbasin001_metalic_0: THREE.Mesh;
    washbasin006_wood_0: THREE.Mesh;
    washbasin008_pink_0: THREE.Mesh;
    Plane009_triangle_0: THREE.Mesh;
    Circle013_red_0: THREE.Mesh;
    Cylinder_cap_0: THREE.Mesh;
    Circle002_metalic_0: THREE.Mesh;
    Cylinder001_tube_0: THREE.Mesh;
    washbasin002_ballon_0: THREE.Mesh;
    board007_red_0: THREE.Mesh;
    board010_wood002_0: THREE.Mesh;
    board009_wood001_0: THREE.Mesh;
    board_dark_blue_0: THREE.Mesh;
    board001_Material004_0: THREE.Mesh;
    board_2006_metalic001_0: THREE.Mesh;
    board_2001_green003_0: THREE.Mesh;
    board_2002_green002_0: THREE.Mesh;
    board_2003_green002_0: THREE.Mesh;
    board_2004_green002_0: THREE.Mesh;
    board_2005_green002_0: THREE.Mesh;
    board_2009_wood002_0: THREE.Mesh;
    board_2007_wood002_0: THREE.Mesh;
    board_2008_green_0: THREE.Mesh;
    board_2_tube_0: THREE.Mesh;
    board_2010_pink_0: THREE.Mesh;
    reel001_red_0: THREE.Mesh;
    reel001_red_0_1: THREE.Mesh;
    Vert002_red_0: THREE.Mesh;
    reel002_red_0: THREE.Mesh;
    reel002_red_0_1: THREE.Mesh;
    reel_red_0: THREE.Mesh;
    reel003_metalic001_0: THREE.Mesh;
    reel004_metalic001_0: THREE.Mesh;
    board_2011_red_0: THREE.Mesh;
    washing_machine_cap_0: THREE.Mesh;
    washing_machine002_Material003_0: THREE.Mesh;
    washing_machine004_Material002_0: THREE.Mesh;
    washing_machine001_Material003_0: THREE.Mesh;
    washing_machine003_Material003_0: THREE.Mesh;
    clock001_Material004_0: THREE.Mesh;
    clock002_dark_blue_0: THREE.Mesh;
    clock003_dark_blue_0: THREE.Mesh;
    clock004_green001_0: THREE.Mesh;
    walls_wood003_0: THREE.Mesh;
    walls001_wood004_0: THREE.Mesh;
    walls002_wood003_0: THREE.Mesh;
    walls003_wood005_0: THREE.Mesh;
    walls004_gray_0: THREE.Mesh;
    walls005_green004_0: THREE.Mesh;
    walls006_glass_0: THREE.Mesh;
    flask005_glass_0: THREE.Mesh;
    flask001_glass_0: THREE.Mesh;
    flask002_wood002_0: THREE.Mesh;
    flask003_glass_0: THREE.Mesh;
    flask004_wood002_0: THREE.Mesh;
    flask_metalic_0: THREE.Mesh;
    flask006_metalic_0: THREE.Mesh;
    flask007_metalic_0: THREE.Mesh;
    flask008_glass_0: THREE.Mesh;
    flask009_glass_0: THREE.Mesh;
    flask010_metalic_0: THREE.Mesh;
    flask011_wood005_0: THREE.Mesh;
    flask012_liquid_0: THREE.Mesh;
    flask013_liquid001_0: THREE.Mesh;
    lamp001_green_0: THREE.Mesh;
    lamp_green001_0: THREE.Mesh;
    lamp002_green_0: THREE.Mesh;
    lamp003_green001_0: THREE.Mesh;
    stand_dark_blue_0: THREE.Mesh;
    Plane002_gray_0: THREE.Mesh;
    legs_wood001_0: THREE.Mesh;
    Plane004_blue_0: THREE.Mesh;
    receiver001_green_0: THREE.Mesh;
    Circle001_green001_0: THREE.Mesh;
    Plane003_green001_0: THREE.Mesh;
    pin005_metalic_0: THREE.Mesh;
    pin001_metalic_0: THREE.Mesh;
    receiver_green002_0: THREE.Mesh;
    Circle_green003_0: THREE.Mesh;
    Plane001_green003_0: THREE.Mesh;
    Plane_wood004_0: THREE.Mesh;
    file001_dark_blue_0: THREE.Mesh;
    file_gray_0: THREE.Mesh;
    file002_green002_0: THREE.Mesh;
    Circle006_blue_0: THREE.Mesh;
    hat001_metalic_0: THREE.Mesh;
    hat_metalic_0: THREE.Mesh;
    hat002_red_0: THREE.Mesh;
    hat003_red_0: THREE.Mesh;
    hat004_red_0: THREE.Mesh;
    hat005_red_0: THREE.Mesh;
    hat006_red_0: THREE.Mesh;
    hat007_dark_blue_0: THREE.Mesh;
    hat008_dark_blue_0: THREE.Mesh;
    hat009_dark_blue_0: THREE.Mesh;
    hat010_dark_blue_0: THREE.Mesh;
    hat011_dark_blue_0: THREE.Mesh;
    pin007_metalic_0: THREE.Mesh;
    cap_red_0: THREE.Mesh;
    cap001_red_0: THREE.Mesh;
    ball_ball_0: THREE.Mesh;
    stand001_blue_0: THREE.Mesh;
    file003_green003_0: THREE.Mesh;
  };
  materials: {
    metalic: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    ['wood.001']: THREE.MeshStandardMaterial;
    ['wood.002']: THREE.MeshStandardMaterial;
    pink: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    triangle: THREE.MeshStandardMaterial;
    material_7: THREE.MeshStandardMaterial;
    tube: THREE.MeshStandardMaterial;
    ballon: THREE.MeshStandardMaterial;
    dark_blue: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['metalic.001']: THREE.MeshStandardMaterial;
    ['green.003']: THREE.MeshStandardMaterial;
    ['green.002']: THREE.MeshStandardMaterial;
    green: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['green.001']: THREE.MeshStandardMaterial;
    ['wood.003']: THREE.MeshStandardMaterial;
    ['wood.004']: THREE.MeshStandardMaterial;
    ['wood.005']: THREE.MeshStandardMaterial;
    gray: THREE.MeshStandardMaterial;
    ['green.004']: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    liquid: THREE.MeshStandardMaterial;
    ['liquid.001']: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    ball: THREE.MeshStandardMaterial;
  };
};

export function Lab(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Lab.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-52.287, 17.147, -292.806]}
        rotation={[-Math.PI / 2, 0, 0.788]}
        scale={31.781}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chair_metalic_0.geometry}
          material={materials.metalic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_red_0.geometry}
          material={materials.material}
          position={[0, 0, 8.243]}
          scale={4.332}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_red_0.geometry}
          material={materials.material}
          position={[2.796, 0, 14.675]}
          rotation={[0, 1.571, 0]}
          scale={4.332}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_metalic_0.geometry}
          material={materials.metalic}
          position={[3.48, 0, 7.559]}
          scale={1.137}
        />
      </group>
      <group
        position={[-1078.792, 1088.817, -649.135]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={17.988}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.reel001_red_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.reel001_red_0_1.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert002_red_0.geometry}
          material={materials.material}
          position={[-0.912, -0.175, 3.394]}
          rotation={[0, 0, 0.331]}
          scale={5.559}
        />
      </group>
      <group
        position={[-1078.792, 1088.817, -582.651]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={17.988}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.reel002_red_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.reel002_red_0_1.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.reel_red_0.geometry}
          material={materials.material}
          position={[-0.872, -0.059, 3.394]}
          scale={5.559}
        />
      </group>
      <group
        position={[-829.455, 461.197, 611.594]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[68.198, 123.959, 123.959]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp001_green_0.geometry}
          material={materials.green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_green001_0.geometry}
          material={materials['green.001']}
          position={[-0.903, 0.002, 0.227]}
          scale={[1.818, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp002_green_0.geometry}
          material={materials.green}
          position={[0.828, 0.009, 2.563]}
          scale={[0.968, 0.919, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp003_green001_0.geometry}
          material={materials['green.001']}
          position={[0, 0.727, 0]}
        />
      </group>
      <group
        position={[-924.989, 419.31, -939.469]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={339.799}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stand_dark_blue_0.geometry}
          material={materials.dark_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_gray_0.geometry}
          material={materials.gray}
          position={[-0.081, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.legs_wood001_0.geometry}
          material={materials['wood.001']}
          position={[2.653, -4.849, -1.184]}
          scale={0.071}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_blue_0.geometry}
          material={materials.blue}
          position={[-0.219, 1.497, -0.384]}
          scale={1.458}
        />
      </group>
      <group
        position={[-715.007, 461.329, -984.529]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[49.336, 81.757, 49.336]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.receiver001_green_0.geometry}
          material={materials.green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_green001_0.geometry}
          material={materials['green.001']}
          position={[1, -0.592, 1.055]}
          rotation={[-1.546, 1.163, -0.507]}
          scale={[0.329, 0.428, 0.462]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_green001_0.geometry}
          material={materials['green.001']}
          position={[0.953, -0.107, 1.053]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.094, 0.057, 0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pin005_metalic_0.geometry}
          material={materials.metalic}
          position={[-0.829, 1, 0.157]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.057, 0.057, 0.034]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pin001_metalic_0.geometry}
          material={materials.metalic}
          position={[5.286, -1.844, 0.243]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.057, 0.034, 0.057]}
        />
      </group>
      <group
        position={[-948.704, 461.329, -889.338]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 165.714, 100]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.receiver_green002_0.geometry}
          material={materials['green.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_green003_0.geometry}
          material={materials['green.003']}
          position={[1, 0.249, 0.831]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.258, 0.156, 0.258]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_green003_0.geometry}
          material={materials['green.003']}
          position={[0.953, -0.858, 0.233]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.094, 0.057, 0.094]}
        />
      </group>
      <group
        position={[-932.835, 461.359, -255.656]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={141.36}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.file001_dark_blue_0.geometry}
          material={materials.dark_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.file_gray_0.geometry}
          material={materials.gray}
          position={[-0.034, 0, 0]}
        />
      </group>
      <group
        position={[-954.72, 461.196, 160.801]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 287.658, 100]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.file002_green002_0.geometry}
          material={materials['green.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_blue_0.geometry}
          material={materials.blue}
          position={[1.055, -0.732, 1.167]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.075, 0.026, 0.075]}
        />
      </group>
      <group
        position={[-349.026, 453.992, 601.078]}
        rotation={[-Math.PI / 2, 0, 2.025]}
        scale={86.337}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat001_metalic_0.geometry}
          material={materials.metalic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat_metalic_0.geometry}
          material={materials.metalic}
          position={[0, -0.031, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat002_red_0.geometry}
          material={materials.material}
          position={[0.155, -0.155, 1.164]}
          rotation={[0.245, 0.234, 0.086]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat003_red_0.geometry}
          material={materials.material}
          position={[-0.646, -0.368, 0.926]}
          rotation={[0.29, -0.764, 0.217]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat004_red_0.geometry}
          material={materials.material}
          position={[0.661, 0.351, 0.916]}
          rotation={[-0.29, 0.764, 0.217]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat005_red_0.geometry}
          material={materials.material}
          position={[0.367, -0.677, 0.894]}
          rotation={[Math.PI / 4, 0.208, -0.347]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat006_red_0.geometry}
          material={materials.material}
          position={[-0.15, 0.696, 0.941]}
          rotation={[-Math.PI / 4, -0.208, -0.347]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat007_dark_blue_0.geometry}
          material={materials.dark_blue}
          position={[0.155, -0.155, 1.164]}
          rotation={[0.245, 0.234, 0.086]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat008_dark_blue_0.geometry}
          material={materials.dark_blue}
          position={[0.367, -0.677, 0.894]}
          rotation={[Math.PI / 4, 0.208, -0.347]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat009_dark_blue_0.geometry}
          material={materials.dark_blue}
          position={[0.661, 0.351, 0.916]}
          rotation={[-0.29, 0.764, 0.217]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat010_dark_blue_0.geometry}
          material={materials.dark_blue}
          position={[-0.646, -0.368, 0.926]}
          rotation={[0.29, -0.764, 0.217]}
          scale={0.117}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hat011_dark_blue_0.geometry}
          material={materials.dark_blue}
          position={[-0.15, 0.696, 0.941]}
          rotation={[-Math.PI / 4, -0.208, -0.347]}
          scale={0.117}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poster_wood001_0.geometry}
        material={materials['wood.001']}
        position={[578.558, 1022.056, -1073.542]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-415.612, -8.035, 674.446]}
        rotation={[-Math.PI / 2, 0, 0.353]}
        scale={[146.355, 80.357, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box001_pink_0.geometry}
        material={materials.pink}
        position={[306.608, -5.305, 684.039]}
        rotation={[-Math.PI / 2, 0, -0.502]}
        scale={[100.782, 55.335, 68.861]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washbasin_metalic_0.geometry}
        material={materials.metalic}
        position={[152.46, 468.879, -1034.332]}
        scale={28.898}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washbasin001_metalic_0.geometry}
        material={materials.metalic}
        position={[201.779, 468.879, -1034.332]}
        scale={15.087}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washbasin006_wood_0.geometry}
        material={materials.wood}
        position={[320.445, 132.698, -722.708]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.586}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washbasin008_pink_0.geometry}
        material={materials.pink}
        position={[156.188, 340.389, -861.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={211.978}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009_triangle_0.geometry}
        material={materials.triangle}
        position={[-238.144, 461.241, 425.733]}
        rotation={[-Math.PI / 2, 0, -0.592]}
        scale={49.631}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013_red_0.geometry}
        material={materials.material}
        position={[-408.323, 473.799, 514.239]}
        rotation={[-Math.PI, 0.773, 1.988]}
        scale={11.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_cap_0.geometry}
        material={materials.material_7}
        position={[-438.028, 468.543, 409.931]}
        rotation={[-0.09, 0.434, 0.038]}
        scale={[12.271, 12.271, 19.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002_metalic_0.geometry}
        material={materials.metalic}
        position={[-408.323, 473.799, 514.239]}
        rotation={[-Math.PI, 0.773, 1.988]}
        scale={11.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_tube_0.geometry}
        material={materials.tube}
        position={[-438.028, 468.543, 409.931]}
        rotation={[-0.09, 0.434, 0.038]}
        scale={[12.271, 12.271, 19.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washbasin002_ballon_0.geometry}
        material={materials.ballon}
        position={[156.188, 340.389, -861.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={211.978}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board007_red_0.geometry}
        material={materials.material}
        position={[-665.007, 845.834, -1072.364]}
        scale={4.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board010_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-722.877, 921.404, -1073.86]}
        scale={76.649}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board009_wood001_0.geometry}
        material={materials['wood.001']}
        position={[-722.877, 921.404, -1073.86]}
        scale={76.649}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_dark_blue_0.geometry}
        material={materials.dark_blue}
        position={[-722.695, 925.494, -1064.587]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board001_Material004_0.geometry}
        material={materials['Material.004']}
        position={[-722.877, 921.404, -1073.86]}
        scale={76.649}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2006_metalic001_0.geometry}
        material={materials['metalic.001']}
        position={[-1080.009, 1088.814, -895.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={16.854}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2001_green003_0.geometry}
        material={materials['green.003']}
        position={[-1087.224, 964.043, -705.267]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={70.782}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2002_green002_0.geometry}
        material={materials['green.002']}
        position={[-1087.223, 832.195, -593.806]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={27.343}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2003_green002_0.geometry}
        material={materials['green.002']}
        position={[-1087.223, 826.895, -768.702]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={34.756}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2004_green002_0.geometry}
        material={materials['green.002']}
        position={[-1087.223, 879.894, -859.683]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={33.766}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2005_green002_0.geometry}
        material={materials['green.002']}
        position={[-1087.223, 1004.441, -598.223]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={24.968}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2009_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-1100.842, 919.481, -730.763]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[161.545, 221.435, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2007_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-1100.842, 919.481, -730.763]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[161.545, 221.435, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2008_green_0.geometry}
        material={materials.green}
        position={[-1100.842, 919.481, -730.763]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[161.545, 221.435, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2_tube_0.geometry}
        material={materials.tube}
        position={[-1087.236, 828.398, -678.823]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[23.629, 12.891, 73.549]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2010_pink_0.geometry}
        material={materials.pink}
        position={[-1087.236, 1030.21, -855.485]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[32.127, 17.527, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.reel003_metalic001_0.geometry}
        material={materials['metalic.001']}
        position={[-1078.792, 1088.817, -582.651]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={17.988}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.reel004_metalic001_0.geometry}
        material={materials['metalic.001']}
        position={[-1078.792, 1088.817, -649.135]}
        rotation={[-Math.PI / 2, 0, 0.331]}
        scale={17.988}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_2011_red_0.geometry}
        material={materials.material}
        position={[-1080.009, 1088.814, -895.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={16.854}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washing_machine_cap_0.geometry}
        material={materials.material_7}
        position={[551.439, 516.894, -1007.382]}
        rotation={[-0.907, 0, 0]}
        scale={28.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washing_machine002_Material003_0.geometry}
        material={materials['Material.003']}
        position={[519.324, 56.928, -604.576]}
        scale={22.488}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washing_machine004_Material002_0.geometry}
        material={materials['Material.002']}
        position={[684.725, 229.625, -838.288]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={234.225}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washing_machine001_Material003_0.geometry}
        material={materials['Material.003']}
        position={[551.439, 516.894, -1007.382]}
        rotation={[-0.907, 0, 0]}
        scale={28.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.washing_machine003_Material003_0.geometry}
        material={materials['Material.003']}
        position={[551.439, 516.894, -1007.382]}
        rotation={[-0.907, 0, 0]}
        scale={28.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clock001_Material004_0.geometry}
        material={materials['Material.004']}
        position={[-26.929, 1240.219, -1073.332]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clock002_dark_blue_0.geometry}
        material={materials.dark_blue}
        position={[-26.929, 1240.219, -1073.332]}
        scale={3.352}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clock003_dark_blue_0.geometry}
        material={materials.dark_blue}
        position={[-26.965, 1239.981, -1057.545]}
        rotation={[0, 0, 2.924]}
        scale={3.151}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clock004_green001_0.geometry}
        material={materials['green.001']}
        position={[-26.929, 1240.219, -1073.332]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls_wood003_0.geometry}
        material={materials['wood.003']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls001_wood004_0.geometry}
        material={materials['wood.004']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls002_wood003_0.geometry}
        material={materials['wood.003']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls003_wood005_0.geometry}
        material={materials['wood.005']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls004_gray_0.geometry}
        material={materials.gray}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls005_green004_0.geometry}
        material={materials['green.004']}
        position={[0, 1092.866, -0.911]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1100.927, 1093.52, 1100.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.walls006_glass_0.geometry}
        material={materials.glass}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask005_glass_0.geometry}
        material={materials.glass}
        position={[-860.546, 546.534, -688.119]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask001_glass_0.geometry}
        material={materials.glass}
        position={[-860.134, 546.534, -672.779]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask002_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-947.484, 819.966, -842.689]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={6.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask003_glass_0.geometry}
        material={materials.glass}
        position={[-860.216, 546.534, -657.351]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask004_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-947.44, 687.337, -645.16]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={6.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask_metalic_0.geometry}
        material={materials.metalic}
        position={[-860.03, 321.412, -772.648]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={104.449}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask006_metalic_0.geometry}
        material={materials.metalic}
        position={[-949.97, 537.211, -843.809]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask007_metalic_0.geometry}
        material={materials.metalic}
        position={[-949.97, 402.293, -646.442]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask008_glass_0.geometry}
        material={materials.glass}
        position={[-947.488, 703.089, -842.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={49.548}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask009_glass_0.geometry}
        material={materials.glass}
        position={[-947.488, 568.17, -645.315]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={49.548}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask010_metalic_0.geometry}
        material={materials.metalic}
        position={[-966.601, 461.216, -992.768]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask011_wood005_0.geometry}
        material={materials['wood.005']}
        position={[-1003.81, 461.206, -979.988]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask012_liquid_0.geometry}
        material={materials.liquid}
        position={[-947.488, 568.17, -645.315]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={45.299}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flask013_liquid001_0.geometry}
        material={materials['liquid.001']}
        position={[-947.488, 703.325, -842.853]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={45.299}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_wood004_0.geometry}
        material={materials['wood.004']}
        position={[-926.294, 620.452, 337.733]}
        rotation={[-Math.PI / 2, 0, 0.582]}
        scale={[20.722, 37.614, 37.614]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pin007_metalic_0.geometry}
        material={materials.metalic}
        position={[-1051.908, 441.39, 789.964]}
        rotation={[0.023, 0, 0]}
        scale={11.434}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cap_red_0.geometry}
        material={materials.material}
        position={[-949.856, 620.771, 11.792]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.766}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cap001_red_0.geometry}
        material={materials.material}
        position={[-714.775, 461.246, 467.888]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={39.754}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ball_ball_0.geometry}
        material={materials.ball}
        position={[-482.963, 496.695, 488.044]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={37.472}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand001_blue_0.geometry}
        material={materials.blue}
        position={[-924.989, 419.31, -939.469]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={339.799}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.file003_green003_0.geometry}
        material={materials['green.003']}
        position={[-954.72, 461.196, 160.801]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 287.658, 100]}
      />
    </group>
  );
}

useGLTF.preload('/models/Lab.glb');
