/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: creosine (https://sketchfab.com/creosine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-low-poly-game-model-14b057db85944e7681a5d68993348f22
Title: old PC low poly game model
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh;
  };
  materials: {
    ['01___Default']: THREE.MeshStandardMaterial;
  };
};

export function RetroComputer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/RetroComputer.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials['01___Default']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.832, 1, 1]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/RetroComputer.glb');
