/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jawlex (https://sketchfab.com/jawlex3d)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-red-apple-365819e9c1de43e6ab24147ee25d4833
Title: Low-Poly Red Apple
*/

import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Head_LP_PM3D_Cylinder3D1_SeamsColor_0: THREE.Mesh;
    Base_LP__0: THREE.Mesh;
  };
  materials: {
    PM3D_Cylinder3D1_SeamsColor: THREE.MeshPhysicalMaterial;
    Base_LP__0: THREE.MeshStandardMaterial;
  };
};

export function Apple(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Apple.glb');
  const rigidBody = useRef();

  const applyImpulse = ({ x, y, z }) => {
    if (rigidBody.current) {
      rigidBody.current.applyImpulse({ x, y, z }, true);
    }
  };

  const handleClick = () => {
    applyImpulse({ x: 0.0, y: 0.001, z: -0.0015 });
  };

  return (
    <RigidBody
      colliders="hull"
      type="dynamic"
      onClick={handleClick}
      restitution={0.2}
      friction={0.7}
      ref={rigidBody}
    >
      <group
        {...props}
        dispose={null}
        onPointerOver={(e) => {
          document.body.style.cursor = 'pointer';
          e.stopPropagation();
        }}
        onPointerOut={() => {
          document.body.style.cursor = 'default';
        }}
      >
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Head_LP_PM3D_Cylinder3D1_SeamsColor_0.geometry}
            material={materials.PM3D_Cylinder3D1_SeamsColor}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_LP__0.geometry}
            material={materials.Base_LP__0}
            position={[0.03, 0.188, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload('/models/Apple.glb');
