/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useFBX, useGLTF, useScroll } from '@react-three/drei';
import { useFrame, useGraph } from '@react-three/fiber';
import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTF, SkeletonUtils } from 'three-stdlib';

import { useMobile } from '@/hooks/use-mobile';

type GLTFResult = GLTF & {
  nodes: {
    EyeLeft: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
      morphTargetDictionary: { [key: string]: number };
      morphTargetInfluences: number[];
    };
    EyeRight: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
      morphTargetDictionary: { [key: string]: number };
      morphTargetInfluences: number[];
    };
    Wolf3D_Head: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
      morphTargetDictionary: { [key: string]: number };
      morphTargetInfluences: number[];
    };
    Wolf3D_Teeth: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
      morphTargetDictionary: { [key: string]: number };
      morphTargetInfluences: number[];
    };
    Wolf3D_Hair: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Wolf3D_Glasses: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Wolf3D_Outfit_Top: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Wolf3D_Body: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry;
      skeleton: THREE.Skeleton;
    };
    Hips: THREE.Bone;
  };
  materials: {
    Wolf3D_Eye: THREE.MeshStandardMaterial;
    Wolf3D_Skin: THREE.MeshStandardMaterial;
    Wolf3D_Teeth: THREE.MeshStandardMaterial;
    Wolf3D_Hair: THREE.MeshStandardMaterial;
    Wolf3D_Glasses: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial;
    Wolf3D_Body: THREE.MeshPhysicalMaterial;
  };
};

export function Avatar(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { isMobile } = useMobile();
  const { scene } = useGLTF('/models/Avatar.glb') as GLTFResult;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { animations: idleAnimation } = useFBX('/models/animations/idle.fbx');
  const { animations: walkingAnimation } = useFBX('/models/animations/walking.fbx');

  idleAnimation[0].name = 'idle';
  walkingAnimation[0].name = 'walking';

  const { actions } = useAnimations([idleAnimation[0], walkingAnimation[0]], group);
  const [currentAnimation, setCurrentAnimation] = useState('idle');
  const scrollData = useScroll();
  const lastScroll = useRef(0);
  const animationTimeout = useRef<NodeJS.Timeout | null>(null);

  // Initialize animations
  useEffect(() => {
    if (!actions) return;

    try {
      if (actions['idle'] && actions['walking']) {
        // Start both animations
        actions['idle'].play();
        actions['walking'].play();

        // Set initial weights
        actions['idle'].setEffectiveWeight(1);
        actions['walking'].setEffectiveWeight(0);

        return () => {
          actions['idle']?.stop();
          actions['walking']?.stop();
        };
      }
    } catch (error) {
      console.warn('Animation initialization error:', error);
    }
  }, [actions]);

  useFrame(() => {
    if (!scrollData || !group.current || !actions) return;

    try {
      const scrollDelta = scrollData.offset - lastScroll.current;
      const isMoving = Math.abs(scrollDelta) > 0.0001;
      let rotationTarget = 0;

      if (isMoving) {
        if (animationTimeout.current) {
          clearTimeout(animationTimeout.current);
        }

        // Use the same rotation logic as the working version
        rotationTarget =
          scrollDelta > 0 ? (isMobile ? Math.PI / 2 : 0) : isMobile ? -Math.PI / 2 : Math.PI;

        if (actions['idle'] && actions['walking']) {
          actions['idle'].setEffectiveWeight(0);
          actions['walking'].setEffectiveWeight(1);

          if (currentAnimation !== 'walking') {
            setCurrentAnimation('walking');
          }
        }
      } else if (currentAnimation !== 'idle') {
        animationTimeout.current = setTimeout(() => {
          if (actions['idle'] && actions['walking']) {
            actions['idle'].setEffectiveWeight(
              THREE.MathUtils.lerp(actions['idle'].getEffectiveWeight(), isMoving ? 0 : 1, 0.1),
            );

            actions['walking'].setEffectiveWeight(
              THREE.MathUtils.lerp(actions['walking'].getEffectiveWeight(), isMoving ? 1 : 0, 0.1),
            );
          }
        }, 150);
      }

      // Smooth rotation
      if (group.current) {
        group.current.rotation.y = THREE.MathUtils.lerp(
          group.current.rotation.y,
          rotationTarget,
          0.07,
        );
      }

      lastScroll.current = scrollData.offset;
    } catch (error) {
      console.warn('Animation frame error:', error);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
    </group>
  );
}

useGLTF.preload('/models/Avatar.glb');
useFBX.preload('/models/animations/idle.fbx');
useFBX.preload('/models/animations/walking.fbx');
