/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Balloon.glb -o src/components/Balloon.jsx -r public
Balloon by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/d1gDDhM7pTf)
*/

import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import React, { useRef, useState } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Balloon007: THREE.Mesh;
  };
  materials: {
    phong1SG: THREE.MeshStandardMaterial;
  };
};

type BalloonProps = {
  color?: string;
  position?: [number, number, number];
} & JSX.IntrinsicElements['group'];

export function Balloon(props: BalloonProps) {
  const { nodes, materials } = useGLTF('/models/Balloon.glb') as GLTFResult;
  const balloonRef = useRef<THREE.Group>(null);
  const [isFlying, setIsFlying] = useState(false);
  const [isVisible, setIsVisible] = useState(true);

  // Store original position for respawning
  const originalPosition = useRef(
    new THREE.Vector3(
      props.position?.[0] || 0,
      props.position?.[1] || 0,
      props.position?.[2] || 0
    )
  );

  useFrame((state, delta) => {
    if (!balloonRef.current || !isFlying) return;

    // Flying away animation
    balloonRef.current.position.y += delta * 2;
    balloonRef.current.position.x +=
      delta * (Math.sin(state.clock.elapsedTime) * 2);
    balloonRef.current.rotation.z += delta * 2;

    // Check if balloon has flown high enough to hide it
    if (balloonRef.current.position.y > 20) {
      setIsVisible(false);
      setIsFlying(false);

      // Respawn balloon after 3 seconds
      setTimeout(() => {
        if (balloonRef.current) {
          balloonRef.current.position.set(
            originalPosition.current.x,
            originalPosition.current.y,
            originalPosition.current.z
          );
          balloonRef.current.rotation.set(0, 0, 0);
          setIsVisible(true);
        }
      }, 3000);
    }
  });

  const handleClick = (e: THREE.Event | React.PointerEvent) => {
    e.stopPropagation();
    if (!isFlying) {
      setIsFlying(true);
    }
  };

  if (!isVisible) return null;

  return (
    <group
      {...props}
      dispose={null}
      ref={balloonRef}
      onClick={handleClick}
      onPointerOver={(e) => {
        document.body.style.cursor = 'pointer';
        e.stopPropagation();
      }}
      onPointerOut={() => {
        document.body.style.cursor = 'default';
      }}
    >
      <mesh geometry={nodes.Balloon007.geometry} material={materials.phong1SG}>
        <meshStandardMaterial
          {...materials.phong1SG}
          color={props.color || '#ff0000'}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/Balloon.glb');
