/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder398_1: THREE.Mesh;
    Cylinder398_2: THREE.Mesh;
    Cylinder400_1: THREE.Mesh;
    Cylinder400_2: THREE.Mesh;
    Cylinder400_3: THREE.Mesh;
  };
  materials: {
    brown: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    L_yellow: THREE.MeshStandardMaterial;
  };
};

export function Lamp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Lamp.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.326, 0.78, -0.505]} rotation={[-1.419, 0.087, 2.088]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder398_1.geometry}
          material={materials.brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder398_2.geometry}
          material={materials.black}
        />
      </group>
      <group position={[0.44, 2.164, -0.331]} rotation={[0, 0, Math.PI / 6]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder400_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder400_2.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder400_3.geometry}
          material={materials.L_yellow}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Lamp.glb');
