/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['LapTop_Cube002-Mesh']: THREE.Mesh;
    ['LapTop_Cube002-Mesh_1']: THREE.Mesh;
    ['LapTop_Cube002-Mesh_2']: THREE.Mesh;
    ['LapTop_Cube002-Mesh_3']: THREE.Mesh;
  };
  materials: {
    DarkGray: THREE.MeshStandardMaterial;
    lighterGray: THREE.MeshStandardMaterial;
    Gray2: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
  };
};

export function Laptop(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Laptop.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['LapTop_Cube002-Mesh'].geometry}
        material={materials.DarkGray}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['LapTop_Cube002-Mesh_1'].geometry}
        material={materials.lighterGray}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['LapTop_Cube002-Mesh_2'].geometry}
        material={materials.Gray2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['LapTop_Cube002-Mesh_3'].geometry}
        material={materials.Screen}
      />
    </group>
  );
}

useGLTF.preload('/models/Laptop.glb');
