/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from '@react-three/drei';
import React from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    mesh485226736: THREE.Mesh;
    mesh485226736_1: THREE.Mesh;
    mesh485226736_2: THREE.Mesh;
    mesh485226736_3: THREE.Mesh;
    mesh256948792: THREE.Mesh;
    mesh256948792_1: THREE.Mesh;
    mesh256948792_2: THREE.Mesh;
    mesh256948792_3: THREE.Mesh;
  };
  materials: {
    mat16: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat17: THREE.MeshStandardMaterial;
    mat15: THREE.MeshStandardMaterial;
    mat25: THREE.MeshStandardMaterial;
  };
};

export const MacBookPro = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/MacBook Pro.glb') as GLTFResult;
  const screenTextture = useTexture('textures/screen.jpg');

  return (
    <group {...props} dispose={null}>
      <mesh position={[0.02, 0.85, -0.66]}>
        <planeGeometry args={[2.55, 1.55]} />
        <meshBasicMaterial map={screenTextture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_1.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_2.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_3.geometry}
        material={materials.mat15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_1.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_2.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_3.geometry}
        material={materials.mat25}
      />
    </group>
  );
}

useGLTF.preload('/models/MacBook Pro.glb');
