/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useEffect, useRef, useState } from 'react';
import { useCursor, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { exploreInfo } from '@/constants';

type GLTFResult = GLTF & {
  nodes: {
    group2028911354: THREE.Mesh;
    group513383197: THREE.Mesh;
    group1044609393: THREE.Mesh;
    group62313567: THREE.Mesh;
    group1018199070: THREE.Mesh;
    group1855928084: THREE.Mesh;
    group2114715230: THREE.Mesh;
    group961800690: THREE.Mesh;
    group2098010904: THREE.Mesh;
    group1048902298: THREE.Mesh;
    group698486446: THREE.Mesh;
    group513376890: THREE.Mesh;
    group2003878409: THREE.Mesh;
    group1278976230: THREE.Mesh;
    group823787471: THREE.Mesh;
    group1640785644: THREE.Mesh;
    group774986514: THREE.Mesh;
    group163990428: THREE.Mesh;
    group502275761: THREE.Mesh;
    group1083102086: THREE.Mesh;
    group1169220911: THREE.Mesh;
    group819034674: THREE.Mesh;
    group2122795285: THREE.Mesh;
    group1086767079: THREE.Mesh;
    group1548836198: THREE.Mesh;
    group1787203505: THREE.Mesh;
    group781068275: THREE.Mesh;
    group1179346883: THREE.Mesh;
    group731433140: THREE.Mesh;
    group1547746947: THREE.Mesh;
    group1121282222: THREE.Mesh;
    group480589545: THREE.Mesh;
    group796041224: THREE.Mesh;
    group1339086745: THREE.Mesh;
    group195866: THREE.Mesh;
    group1743123278: THREE.Mesh;
    group1580040935: THREE.Mesh;
    group804677075: THREE.Mesh;
  };
  materials: {
    mat17: THREE.MeshStandardMaterial;
    mat8: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
    mat16: THREE.MeshStandardMaterial;
    mat10: THREE.MeshStandardMaterial;
  };
};

export function Mailbox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Mailbox.glb') as GLTFResult;
  const [mailBoxHovered, setMailBoxHovered] = useState(false);

  useCursor(mailBoxHovered);

  useEffect(() => {
    const emissiveColor = new THREE.Color('#ffc527');
    Object.values(materials).forEach((material) => {
      material.emissive = emissiveColor;
    });
  }, [materials]);

  useFrame(() => {
    Object.values(materials).forEach((material) => {
      material.emissiveIntensity = THREE.MathUtils.lerp(
        material.emissiveIntensity,
        mailBoxHovered ? 0.32 : 0,
        0.1
      );
    });
  });

  return (
    <group
      {...props}
      dispose={null}
      onPointerEnter={() => setMailBoxHovered(true)}
      onPointerLeave={() => setMailBoxHovered(false)}
      onClick={() => window.open(`mailto:${exploreInfo.contact.mail}`)}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2028911354.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group513383197.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1044609393.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group62313567.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1018199070.geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1855928084.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2114715230.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group961800690.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2098010904.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1048902298.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group698486446.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group513376890.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2003878409.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1278976230.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group823787471.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1640785644.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group774986514.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group163990428.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group502275761.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1083102086.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1169220911.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group819034674.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2122795285.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1086767079.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1548836198.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1787203505.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group781068275.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1179346883.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group731433140.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1547746947.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1121282222.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group480589545.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group796041224.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1339086745.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group195866.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1743123278.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1580040935.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group804677075.geometry}
        material={materials.mat20}
      />
    </group>
  );
}

useGLTF.preload('/models/Mailbox.glb');
