/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Author: Wen Yeh (https://sketchfab.com/wenyeh1110)
 * License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
 * Source: https://sketchfab.com/3d-models/bird-orange-0d31748606c2499fb652c0c1052b7cfa
 * Title: Bird Orange
 */
import { useGLTF, useAnimations } from '@react-three/drei';
import { useGraph } from '@react-three/fiber';
import React, { useEffect } from 'react';
import * as THREE from 'three';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_51: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    BirdOrange_LMB: THREE.MeshPhysicalMaterial;
  };
};

type ActionName = 'anim';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function OrangeBird(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF('/models/OrangeBird.glb') as GLTFResult;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group) as unknown as {
    actions: GLTFActions;
  };

  useEffect(() => {
    if (actions && actions['anim']) {
      actions['anim'].reset().fadeIn(0.5).play();
    }
    return () => {
      if (actions && actions['anim']) {
        actions['anim'].fadeOut(0.5);
      }
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={46.683}
        >
          <group
            name="bfb1ea86655f4c4ab4c6cbbb449cedf4fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="BirdOrange_all">
                  <group
                    name="Main"
                    position={[-0.083, 0, 0.451]}
                    rotation={[0, -0.074, 0]}
                  >
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_51"
                        geometry={
                          (nodes.Object_51 as THREE.SkinnedMesh).geometry
                        }
                        material={materials.BirdOrange_LMB}
                        skeleton={
                          (nodes.Object_51 as THREE.SkinnedMesh).skeleton
                        }
                      />
                      <group name="Object_50" />
                    </group>
                  </group>
                  <group name="Geometry">
                    <group name="BirdOrange" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/OrangeBird.glb');
