/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MaX3Dd (https://sketchfab.com/MaX3Dd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/whiteboard-low-poly-f69949960b5049f0b7a733e47d9da489
Title: Whiteboard Low-poly
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    White_board_White_board_0: THREE.Mesh;
  };
  materials: {
    White_board: THREE.MeshStandardMaterial;
  };
};

export function Whiteboard(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Whiteboard.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.White_board_White_board_0.geometry}
        material={materials.White_board}
        position={[0, 0.341, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('/models/Whiteboard.glb');
