/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BirchTree.glb -o src/explore/components/BirchTree.jsx -r public 
Author: Alan Zimmerman (https://sketchfab.com/nenjo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/birch-tree-low-poly-1d7f142738604975bbf1b03338a024dd
Title: Birch Tree - Low Poly
*/

import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import { useEffect } from 'react';
import { useMemo } from 'react';
import { useRef } from 'react';

export function BirchTree(props) {
  const group = useRef();
  const { scene, animations } = useGLTF('/models/BirchTree.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  animations[0].name = 'sway';

  useEffect(() => {
    if (actions && actions['sway']) {
      actions['sway'].reset().fadeIn(0.5).play();
    }

    return () => {
      if (actions && actions['sway']) {
        actions['sway'].fadeOut(0.5);
      }
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="0531b0aee76e437286fa1480cfa5eaf0fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={491.491}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_10"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={72.086}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.Tree}
                      skeleton={nodes.Object_11.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Icosphere001"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={72.086}
                />
                <group
                  name="Sun002"
                  position={[755.46, 898.84, 279.323]}
                  rotation={[0.304, -0.087, -1.384]}
                  scale={100}
                >
                  <group name="Object_14" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_15" />
                  </group>
                </group>
                <group
                  name="Sun001"
                  position={[755.46, 898.84, 279.323]}
                  rotation={[-1.336, 0.374, 0.627]}
                  scale={100}
                >
                  <group name="Object_17" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_18" />
                  </group>
                </group>
                <group
                  name="Sun"
                  position={[755.46, 898.84, 279.323]}
                  rotation={[0.585, -0.547, -0.304]}
                  scale={100}
                >
                  <group name="Object_20" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_21" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[748.113, 534.367, 650.764]}
                  rotation={[3.127, 0.756, 2.69]}
                  scale={100}
                >
                  <group name="Object_23" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/BirchTree.glb');
