/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Lab.glb -o src/explore/components/Lab.jsx -r public 
Author: julianikonenko (https://sketchfab.com/julianikonenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rick-and-morty-lab-a55ff01c81de409c8b127c5d39460352
Title: rick and morty lab
*/

import { useGLTF } from '@react-three/drei';

export function Lab(props) {
  const { nodes, materials } = useGLTF('/models/Lab.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane006_red_0.geometry}
        material={materials.material}
        position={[-52.287, 279.1, -292.806]}
        rotation={[-Math.PI / 2, 0, 0.788]}
        scale={137.683}
      />
      <mesh
        geometry={nodes.poster_wood001_0.geometry}
        material={materials['wood.001']}
        position={[578.558, 1022.056, -1073.542]}
        scale={100}
      />
      <mesh
        geometry={nodes.box_wood002_0.geometry}
        material={materials['wood.002']}
        position={[-415.612, -8.035, 674.446]}
        rotation={[-Math.PI / 2, 0, 0.353]}
        scale={[146.355, 80.357, 100]}
      />
      <mesh
        geometry={nodes.box001_pink_0.geometry}
        material={materials.pink}
        position={[306.608, -5.305, 684.039]}
        rotation={[-Math.PI / 2, 0, -0.502]}
        scale={[100.782, 55.335, 68.861]}
      />
      <mesh
        geometry={nodes.washbasin006_wood_0.geometry}
        material={materials.wood}
        position={[320.445, 132.698, -722.708]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.586}
      />
      <mesh
        geometry={nodes.Plane009_triangle_0.geometry}
        material={materials.triangle}
        position={[-238.144, 461.241, 425.733]}
        rotation={[-Math.PI / 2, 0, -0.592]}
        scale={49.631}
      />
      <mesh
        geometry={nodes.Cylinder_cap_0.geometry}
        material={materials.material_7}
        position={[-438.028, 468.543, 409.931]}
        rotation={[-0.09, 0.434, 0.038]}
        scale={[12.271, 12.271, 19.476]}
      />
      <mesh
        geometry={nodes.Cylinder001_tube_0.geometry}
        material={materials.tube}
        position={[-438.028, 468.543, 409.931]}
        rotation={[-0.09, 0.434, 0.038]}
        scale={[12.271, 12.271, 19.476]}
      />
      <mesh
        geometry={nodes.washbasin002_ballon_0.geometry}
        material={materials.ballon}
        position={[156.188, 340.389, -861.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={211.978}
      />
      <mesh
        geometry={nodes.board_dark_blue_0.geometry}
        material={materials.dark_blue}
        position={[-722.695, 925.494, -1064.587]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.board_2006_metalic001_0.geometry}
        material={materials['metalic.001']}
        position={[-1080.009, 1088.814, -895.494]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={16.854}
      />
      <mesh
        geometry={nodes.board_2001_green003_0.geometry}
        material={materials['green.003']}
        position={[-1087.224, 964.043, -705.267]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={70.782}
      />
      <mesh
        geometry={nodes.board_2008_green_0.geometry}
        material={materials.green}
        position={[-1100.842, 919.481, -730.763]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[161.545, 221.435, 100]}
      />
      <mesh
        geometry={nodes.washing_machine002_Material003_0.geometry}
        material={materials['Material.003']}
        position={[519.324, 56.928, -604.576]}
        scale={22.488}
      />
      <mesh
        geometry={nodes.washing_machine004_Material002_0.geometry}
        material={materials['Material.002']}
        position={[684.725, 229.625, -838.288]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={234.225}
      />
      <mesh
        geometry={nodes.clock004_green001_0.geometry}
        material={materials['green.001']}
        position={[-26.929, 1240.219, -1073.332]}
        scale={100}
      />
      <mesh
        geometry={nodes.walls_wood003_0.geometry}
        material={materials['wood.003']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        geometry={nodes.walls001_wood004_0.geometry}
        material={materials['wood.004']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        geometry={nodes.walls003_wood005_0.geometry}
        material={materials['wood.005']}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        geometry={nodes.walls004_gray_0.geometry}
        material={materials.gray}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        geometry={nodes.walls005_green004_0.geometry}
        material={materials['green.004']}
        position={[0, 1092.866, -0.911]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1100.927, 1093.52, 1100.927]}
      />
      <mesh
        geometry={nodes.walls006_glass_0.geometry}
        material={materials.glass}
        position={[0, 1092.866, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1100.927}
      />
      <mesh
        geometry={nodes.flask_metalic_0.geometry}
        material={materials.metalic}
        position={[-860.03, 321.412, -772.648]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={104.449}
      />
      <mesh
        geometry={nodes.flask008_glass_0.geometry}
        material={materials.glass}
        position={[-947.488, 703.089, -842.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={49.548}
      />
      <mesh
        geometry={nodes.Plane004_blue_0.geometry}
        material={materials.blue}
        position={[-999.427, 288.79, -1447.994]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={495.413}
      />
      <mesh
        geometry={nodes.receiver_green002_0.geometry}
        material={materials['green.002']}
        position={[-948.704, 461.329, -889.338]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 165.714, 100]}
      />
      <mesh
        geometry={nodes.ball_ball_0.geometry}
        material={materials.ball}
        position={[-482.963, 496.695, 488.044]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={37.472}
      />
      <instancedMesh
        args={[nodes.board_2002_green002_0.geometry, materials['green.002'], 4]}
        instanceMatrix={nodes.board_2002_green002_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.reel001_red_0.geometry, materials.material, 2]}
        instanceMatrix={nodes.reel001_red_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.reel001_red_0_1.geometry, materials.material, 2]}
        instanceMatrix={nodes.reel001_red_0_1.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.reel003_metalic001_0.geometry,
          materials['metalic.001'],
          2,
        ]}
        instanceMatrix={nodes.reel003_metalic001_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.flask005_glass_0.geometry, materials.glass, 3]}
        instanceMatrix={nodes.flask005_glass_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.flask012_liquid_0.geometry, materials.liquid, 2]}
        instanceMatrix={nodes.flask012_liquid_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.hat002_red_0.geometry, materials.material, 5]}
        instanceMatrix={nodes.hat002_red_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.hat007_dark_blue_0.geometry, materials.dark_blue, 5]}
        instanceMatrix={nodes.hat007_dark_blue_0.instanceMatrix}
      />
      <mesh
        geometry={nodes.chair_metalic_0.geometry}
        material={materials.metalic}
        position={[-52.287, 17.147, -292.806]}
        rotation={[-Math.PI / 2, 0, 0.788]}
        scale={31.781}
      />
      <mesh
        geometry={nodes.board001_Material004_0.geometry}
        material={materials['Material.004']}
        position={[-722.877, 921.404, -1073.86]}
        scale={76.649}
      />
    </group>
  );
}

useGLTF.preload('/models/Lab.glb');
