/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Tree.glb -o src/explore/components/Tree.jsx -r public 
Author: Coco Jinjo (https://sketchfab.com/Estelle.Ggo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tree-843278c62cb9494bafda67e7c14c5707
Title: Stylized Tree
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Tree(props) {
  const group = React.useRef();
  const { nodes, materials } = useGLTF('/models/Tree.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={12.632}
        >
          <group name="Tree_1fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group4" scale={3.533}>
                  <group name="Tree">
                    <group name="group10" position={[0, 0, -9.674]}>
                      <group name="group12" position={[0, 0, 9.674]}>
                        <group
                          name="polySurface63"
                          position={[-0.286, 10.272, 0.342]}
                          rotation={[1.268, 0.596, 2.962]}
                        >
                          <mesh
                            name="polySurface63_lambert3_0"
                            geometry={nodes.polySurface63_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface72"
                          position={[-2.744, 14.905, 5.396]}
                          rotation={[1.205, 0.969, -3.073]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface72_lambert3_0"
                            geometry={nodes.polySurface72_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface54"
                          position={[-5.264, 8.536, 13.29]}
                          rotation={[-1.605, -0.284, -0.426]}
                          scale={[0.779, 0.865, 0.864]}
                        >
                          <mesh
                            name="polySurface54_lambert3_0"
                            geometry={nodes.polySurface54_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface24"
                          position={[-5.274, 2.103, 5.214]}
                          rotation={[-1.044, -0.832, -0.55]}
                        >
                          <mesh
                            name="polySurface24_lambert3_0"
                            geometry={nodes.polySurface24_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface26"
                          position={[-10.986, 9.689, 8.428]}
                          rotation={[2.187, 0.044, -2.058]}
                          scale={[0.834, 0.801, 0.872]}
                        >
                          <mesh
                            name="polySurface26_lambert3_0"
                            geometry={nodes.polySurface26_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface57"
                          position={[0.362, 2.783, -8.543]}
                          rotation={[-2.305, 0.67, 2.894]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface57_lambert3_0"
                            geometry={nodes.polySurface57_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface11"
                          position={[-1.76, 16.41, 13.489]}
                          rotation={[1.174, 0.612, 3.105]}
                          scale={[0.803, 0.87, 0.834]}
                        >
                          <mesh
                            name="polySurface11_lambert3_0"
                            geometry={nodes.polySurface11_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface56"
                          position={[-0.734, 4.079, -11.754]}
                          rotation={[-2.191, 0.276, 3.141]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface56_lambert3_0"
                            geometry={nodes.polySurface56_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface42"
                          position={[-3.116, 14.274, 6.517]}
                          rotation={[1.29, 0.484, -3.025]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface42_lambert3_0"
                            geometry={nodes.polySurface42_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface6"
                          position={[-2.439, 8.772, -12.588]}
                          rotation={[-1.709, -0.038, -2.871]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface6_lambert3_0"
                            geometry={nodes.polySurface6_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface49"
                          position={[-6.3, 2.829, 12.2]}
                          rotation={[-1.101, -0.543, -0.406]}
                          scale={[0.79, 0.866, 0.851]}
                        >
                          <mesh
                            name="polySurface49_lambert3_0"
                            geometry={nodes.polySurface49_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface8"
                          position={[5.537, 8.555, 1.45]}
                          rotation={[2.512, 0.265, 2.13]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface8_lambert3_0"
                            geometry={nodes.polySurface8_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface48"
                          position={[-5.026, 3.797, 9.64]}
                          rotation={[-1.035, -0.426, -0.243]}
                        >
                          <mesh
                            name="polySurface48_lambert3_0"
                            geometry={nodes.polySurface48_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface64"
                          position={[-1.818, 10.465, 11.111]}
                          rotation={[-1.566, -0.253, -0.254]}
                        >
                          <mesh
                            name="polySurface64_lambert3_0"
                            geometry={nodes.polySurface64_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface12"
                          position={[-1.831, 4.079, -11.761]}
                          rotation={[-2.191, 0.276, 3.141]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface12_lambert3_0"
                            geometry={nodes.polySurface12_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface50"
                          position={[-2.163, 19.502, -4.169]}
                          rotation={[1.903, 1.458, 0.575]}
                          scale={[0.867, 0.872, 0.77]}
                        >
                          <mesh
                            name="polySurface50_lambert3_0"
                            geometry={nodes.polySurface50_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface15"
                          position={[-0.269, 23.843, -8.992]}
                          rotation={[-0.564, 1.374, 3.075]}
                        >
                          <mesh
                            name="polySurface15_lambert3_0"
                            geometry={nodes.polySurface15_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface44"
                          position={[6.959, 15.146, -3.841]}
                          rotation={[2.261, 0.176, 1.305]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface44_lambert3_0"
                            geometry={nodes.polySurface44_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group name="polySurface2">
                          <mesh
                            name="polySurface2_lambert3_0"
                            geometry={nodes.polySurface2_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface22"
                          position={[7.694, 4.023, 6.622]}
                          rotation={[-0.976, 0.264, 0.68]}
                        >
                          <mesh
                            name="polySurface22_lambert3_0"
                            geometry={nodes.polySurface22_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface19"
                          position={[-8.581, 19.352, 7.833]}
                          rotation={[0.826, 0.171, -2.348]}
                        >
                          <mesh
                            name="polySurface19_lambert3_0"
                            geometry={nodes.polySurface19_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface35"
                          position={[-2.125, -0.452, 4.144]}
                          rotation={[0, -0.136, 0]}
                          scale={[0.765, 0.872, 0.872]}
                        >
                          <mesh
                            name="polySurface35_lambert3_0"
                            geometry={nodes.polySurface35_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface21"
                          position={[4.532, 17.251, -11.452]}
                          rotation={[1.973, -0.392, 0.401]}
                        >
                          <mesh
                            name="polySurface21_lambert3_0"
                            geometry={nodes.polySurface21_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface39"
                          position={[-2.45, 1.174, -3.613]}
                          rotation={[-Math.PI, -0.273, -Math.PI]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface39_lambert3_0"
                            geometry={nodes.polySurface39_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface5"
                          position={[4.311, 18.602, 3.569]}
                          rotation={[0.121, 0.139, 2.41]}
                          scale={[0.814, 0.827, 0.865]}
                        >
                          <mesh
                            name="polySurface5_lambert3_0"
                            geometry={nodes.polySurface5_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface58"
                          position={[3.163, 9.453, -11.004]}
                          rotation={[0.978, 0.186, 0.685]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface58_lambert3_0"
                            geometry={nodes.polySurface58_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface51"
                          position={[-7.718, 8.788, -4.287]}
                          rotation={[0.756, -0.638, -0.773]}
                          scale={[0.836, 0.824, 0.846]}
                        >
                          <mesh
                            name="polySurface51_lambert3_0"
                            geometry={nodes.polySurface51_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface66"
                          position={[-2.887, 10.066, 11.4]}
                          rotation={[-1.985, -1.243, -0.644]}
                        >
                          <mesh
                            name="polySurface66_lambert3_0"
                            geometry={nodes.polySurface66_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface37"
                          position={[-7.314, 18.688, -1.297]}
                          rotation={[3.003, -0.512, -0.726]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface37_lambert3_0"
                            geometry={nodes.polySurface37_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface73"
                          position={[-8.618, 14.631, 2.693]}
                          rotation={[0.583, 0.529, -2.227]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface73_lambert3_0"
                            geometry={nodes.polySurface73_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface10"
                          position={[7.499, 13.936, 2.424]}
                          rotation={[2.116, 0.1, 1.335]}
                          scale={[0.857, 0.779, 0.872]}
                        >
                          <mesh
                            name="polySurface10_lambert3_0"
                            geometry={nodes.polySurface10_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface4"
                          position={[-9.949, 16.031, -5.494]}
                          rotation={[0.925, -0.425, -1.253]}
                        >
                          <mesh
                            name="polySurface4_lambert3_0"
                            geometry={nodes.polySurface4_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface46"
                          position={[0.766, 18.688, -9.992]}
                          rotation={[0.349, 1.212, 2.154]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface46_lambert3_0"
                            geometry={nodes.polySurface46_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface33"
                          position={[-10.487, 15.549, 9.236]}
                          rotation={[0.812, 0.101, -2.184]}
                          scale={[0.823, 0.815, 0.869]}
                        >
                          <mesh
                            name="polySurface33_lambert3_0"
                            geometry={nodes.polySurface33_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface69"
                          position={[-8.267, 9.645, -9.184]}
                          rotation={[0.696, -0.48, -0.832]}
                        >
                          <mesh
                            name="polySurface69_lambert3_0"
                            geometry={nodes.polySurface69_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface52"
                          position={[-5.986, 14.981, -4.858]}
                          rotation={[1.615, -0.612, -0.411]}
                          scale={[0.817, 0.85, 0.839]}
                        >
                          <mesh
                            name="polySurface52_lambert3_0"
                            geometry={nodes.polySurface52_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface70"
                          position={[-1.517, 22.885, -9.426]}
                          rotation={[2.586, 1.341, -0.115]}
                        >
                          <mesh
                            name="polySurface70_lambert3_0"
                            geometry={nodes.polySurface70_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface27"
                          position={[-10.322, 13.176, -2.306]}
                          rotation={[2.172, 0.273, -0.951]}
                          scale={[0.844, 0.794, 0.869]}
                        >
                          <mesh
                            name="polySurface27_lambert3_0"
                            geometry={nodes.polySurface27_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface47"
                          position={[-9.486, 4.253, -6.907]}
                          rotation={[-2.084, -0.408, -2.216]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface47_lambert3_0"
                            geometry={nodes.polySurface47_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface17"
                          position={[-9.665, 10.818, 7.323]}
                          rotation={[2.188, -0.031, -2.231]}
                        >
                          <mesh
                            name="polySurface17_lambert3_0"
                            geometry={nodes.polySurface17_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface9"
                          position={[4.152, 14.459, 2.659]}
                          rotation={[1.783, 0.515, 2.291]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface9_lambert3_0"
                            geometry={nodes.polySurface9_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface45"
                          position={[-2.45, 1.174, -3.613]}
                          rotation={[-Math.PI, -0.273, -Math.PI]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface45_lambert3_0"
                            geometry={nodes.polySurface45_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface61"
                          position={[11.718, 17.07, -4.399]}
                          rotation={[2.124, 0.026, 1.175]}
                        >
                          <mesh
                            name="polySurface61_lambert3_0"
                            geometry={nodes.polySurface61_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface32"
                          position={[-10.735, 15.228, -0.167]}
                          rotation={[0.989, -0.466, -1.487]}
                          scale={[0.872, 0.778, 0.858]}
                        >
                          <mesh
                            name="polySurface32_lambert3_0"
                            geometry={nodes.polySurface32_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface13"
                          position={[-2.673, 8.878, -12.611]}
                          rotation={[-1.987, 1.243, -2.914]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface13_lambert3_0"
                            geometry={nodes.polySurface13_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface41"
                          position={[2.259, 15.984, -11.156]}
                          rotation={[2.26, -0.351, 0.581]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface41_lambert3_0"
                            geometry={nodes.polySurface41_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface67"
                          position={[-3.175, 9.929, 11.29]}
                          rotation={[-1.428, 0, 0]}
                        >
                          <mesh
                            name="polySurface67_lambert3_0"
                            geometry={nodes.polySurface67_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface29"
                          position={[-7.932, 19.212, 9.772]}
                          rotation={[2.969, -0.876, -0.805]}
                          scale={[0.857, 0.853, 0.797]}
                        >
                          <mesh
                            name="polySurface29_lambert3_0"
                            geometry={nodes.polySurface29_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface7"
                          position={[-3.401, 9.183, -12.177]}
                          rotation={[-1.645, 0.242, -3.114]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface7_lambert3_0"
                            geometry={nodes.polySurface7_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface60"
                          position={[-0.397, 19.422, 2.959]}
                          rotation={[-0.785, -1.422, 1.74]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface60_lambert3_0"
                            geometry={nodes.polySurface60_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface53"
                          position={[-5.613, 8.389, 13.582]}
                          rotation={[-2.321, -1.205, -1.004]}
                          scale={[0.866, 0.868, 0.775]}
                        >
                          <mesh
                            name="polySurface53_lambert3_0"
                            geometry={nodes.polySurface53_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface25"
                          position={[-6.771, 1.463, 7.767]}
                          rotation={[-1.207, -0.956, -0.779]}
                          scale={[0.839, 0.859, 0.809]}
                        >
                          <mesh
                            name="polySurface25_lambert3_0"
                            geometry={nodes.polySurface25_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface34"
                          position={[-9.008, 13.904, -1.056]}
                          rotation={[0.988, -0.555, -1.156]}
                          scale={[0.864, 0.792, 0.851]}
                        >
                          <mesh
                            name="polySurface34_lambert3_0"
                            geometry={nodes.polySurface34_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface68"
                          position={[6.937, 22.885, -1.202]}
                          rotation={[0.124, 0.241, 2.454]}
                        >
                          <mesh
                            name="polySurface68_lambert3_0"
                            geometry={nodes.polySurface68_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface43"
                          position={[6.016, 13.442, -1.616]}
                          rotation={[2.292, 0.252, 1.664]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface43_lambert3_0"
                            geometry={nodes.polySurface43_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface31"
                          position={[3.833, 3.383, 9.865]}
                          rotation={[-0.946, 0.221, 0.624]}
                          scale={[0.814, 0.829, 0.864]}
                        >
                          <mesh
                            name="polySurface31_lambert3_0"
                            geometry={nodes.polySurface31_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface30"
                          position={[-8.54, 14.966, -4.08]}
                          rotation={[1.429, -0.591, -0.772]}
                          scale={[0.841, 0.822, 0.843]}
                        >
                          <mesh
                            name="polySurface30_lambert3_0"
                            geometry={nodes.polySurface30_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface28"
                          position={[-1.264, 20.34, -3.664]}
                          rotation={[-0.321, 1.274, 2.824]}
                          scale={[0.868, 0.872, 0.769]}
                        >
                          <mesh
                            name="polySurface28_lambert3_0"
                            geometry={nodes.polySurface28_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface59"
                          position={[7.08, 13.788, -0.711]}
                          rotation={[0.923, -0.008, 1.912]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface59_lambert3_0"
                            geometry={nodes.polySurface59_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface20"
                          position={[-12.151, 18.257, -2.198]}
                          rotation={[0.938, -0.344, -1.614]}
                        >
                          <mesh
                            name="polySurface20_lambert3_0"
                            geometry={nodes.polySurface20_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface55"
                          position={[-5.865, 8.209, 13.573]}
                          rotation={[-1.429, -0.019, -0.134]}
                          scale={[0.765, 0.872, 0.872]}
                        >
                          <mesh
                            name="polySurface55_lambert3_0"
                            geometry={nodes.polySurface55_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface36"
                          position={[-2.125, -0.452, 4.144]}
                          rotation={[0, -0.136, 0]}
                          scale={[0.765, 0.872, 0.872]}
                        >
                          <mesh
                            name="polySurface36_lambert3_0"
                            geometry={nodes.polySurface36_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface14"
                          position={[0.612, 18.688, 3.022]}
                          rotation={[0.262, -1.088, 2.716]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface14_lambert3_0"
                            geometry={nodes.polySurface14_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface18"
                          position={[-10.969, 16.482, -7.007]}
                          rotation={[2.199, 0.171, -1.01]}
                        >
                          <mesh
                            name="polySurface18_lambert3_0"
                            geometry={nodes.polySurface18_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface65"
                          position={[-6.099, 17.358, -10.217]}
                          rotation={[1.519, -0.552, -0.536]}
                        >
                          <mesh
                            name="polySurface65_lambert3_0"
                            geometry={nodes.polySurface65_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface38"
                          position={[-9.49, 14.238, 2.51]}
                          rotation={[1.028, 0.117, -2.2]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface38_lambert3_0"
                            geometry={nodes.polySurface38_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface23"
                          position={[-7.299, 2.829, 11.715]}
                          rotation={[-1.101, -0.543, -0.406]}
                          scale={[0.79, 0.866, 0.851]}
                        >
                          <mesh
                            name="polySurface23_lambert3_0"
                            geometry={nodes.polySurface23_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface62"
                          position={[-3.647, 3.797, 10.035]}
                          rotation={[-1.035, -0.426, -0.243]}
                        >
                          <mesh
                            name="polySurface62_lambert3_0"
                            geometry={nodes.polySurface62_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group name="polySurface1">
                          <mesh
                            name="polySurface1_lambert3_0"
                            geometry={nodes.polySurface1_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface16"
                          position={[-6.293, 22.885, 6.894]}
                          rotation={[2.934, -0.949, -0.828]}
                        >
                          <mesh
                            name="polySurface16_lambert3_0"
                            geometry={nodes.polySurface16_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface40"
                          position={[-6.487, 15.96, -11.411]}
                          rotation={[1.679, -0.653, -0.509]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface40_lambert3_0"
                            geometry={nodes.polySurface40_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group name="polySurface3">
                          <mesh
                            name="polySurface3_lambert3_0"
                            geometry={nodes.polySurface3_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                        <group
                          name="polySurface71"
                          position={[-1.101, 10.403, 6.288]}
                          rotation={[1.765, 0.597, 3.079]}
                          scale={0.765}
                        >
                          <mesh
                            name="polySurface71_lambert3_0"
                            geometry={nodes.polySurface71_lambert3_0.geometry}
                            material={materials.lambert3}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/Tree.glb');
