import type { Project } from "@/lib/types/index";
import { projectsArraySchema } from "@/lib/validations/constants";

const rawProjects: Project[] = [
  {
    client: "Personal Project",
    description:
      "**Zucchini** is a **local-first desktop habit tracker** built for people who want consistent daily momentum without handing their routines over to a cloud service.",
    features: [
      "**Local-first tracking** with on-device storage",
      "**Fast daily check-ins** for regular routines",
      "**Streaks and freezes** that protect consistency",
      "**Desktop reminders** for low-friction habits",
      "**History and reviews** to spot progress trends",
    ],
    github: "https://github.com/Benjam11n/zucchini",
    hero_image: "/projects/zucchini/hero.png",
    href: "https://zucchini.codedbyben.com/",
    id: "zucchini",
    location: "Singapore",
    logo: "/projects/zucchini/logo.png",
    logoStyle: {
      backgroundColor: "#0f291d",
      border: "0.2px solid #28503e",
      boxShadow: "0px 0px 60px 0px #6bbf7a4d",
    },
    preview_poster: "/projects/zucchini/preview-poster.jpg",
    preview_video: "/projects/zucchini/preview.mp4",
    services: "Desktop App, Productivity",
    status: "in-development",
    subdesc:
      "Built with **Electron, React, TypeScript, SQLite, Drizzle ORM, Vite**, **Framer Motion**, and **Tailwind CSS**, **Zucchini** focuses on fast daily check-ins, reminder-driven routines, streak protection, and clear weekly review feedback while keeping your data on your own machine.",
    techStack: [
      "Electron",
      "React",
      "TypeScript",
      "SQLite",
      "Drizzle ORM",
      "Vite",
      "Framer",
      "Tailwind",
      "Zustand",
    ],
    title: "Zucchini - Local-First Habit Tracker",
    video_overview: "/projects/zucchini/video.mp4",
    year: "2026",
  },
  {
    client: "Hackathon",
    description:
      "Pioneering a **tele-rehabilitation platform** that combines **real-time computer vision** with **biomechanical analysis**.",
    features: [
      "**Real-time pose detection** with **extremely high accuracy**",
      "**30fps video streams** via **WebSockets**",
      "**Custom pose smoothing** algorithms",
      "**Microservices architecture** for ML inference",
      "**Complex rehabilitation metrics** tracking",
      "**Gamified recovery** visualization",
    ],
    github: "https://github.com/Benjam11n/disknee",
    hero_image: "/projects/disknee/hero.png",
    id: "disknee",
    location: "Singapore",
    logo: "/projects/disknee/logo.png",
    logoStyle: {
      backgroundColor: "#0a1628",
      border: "0.2px solid #1e3a5f",
      boxShadow: "0px 0px 60px 0px #2563eb4D",
    },
    preview_poster: "/projects/disknee/preview-poster.jpg",
    preview_video: "/projects/disknee/preview.mp4",
    services: "Computer Vision, Healthcare Tech",
    subdesc:
      "**DisKnee** revolutionizes knee recovery by delivering **precise movement tracking** and instant feedback without expensive hardware. Built with a high-performance **WebSocket infrastructure** handling **30fps video streams**, integrated **Google MediaPipe** with custom pose smoothing algorithms achieving **extremely high pose detection accuracy**.",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind",
      "Python",
      "PyTorch",
      "FastAPI",
      "WebSocket",
      "MediaPipe",
      "Supabase",
    ],
    title:
      "DisKnee - Advanced Computer Vision Platform for Sports Medicine & Rehabilitation",
    video_overview: "/projects/disknee/video.mp4",
    year: "2025",
  },
  {
    client: "Hackathon",
    description:
      "A platform that uses **AI-powered digital twins** to revolutionize **mental health therapy** and treatment.",
    features: [
      "**Real-time voice-based** therapy sessions",
      "**Interactive AI** patient simulations",
      "**Contextual, condition-specific** responses",
      "**Learning** from therapeutic techniques",
      "**Seamless voice processing** interaction",
    ],
    github: "https://github.com/Benjam11n/TwinAI",
    hero_image: "/projects/twinAI/hero.png",
    id: "twinAI",
    location: "Singapore",
    logo: "/projects/twinAI/logo.png",
    logoStyle: {
      backgroundColor: "#151a11",
      border: "0.2px solid #233814",
      boxShadow: "0px 0px 60px 0px #324d1f",
    },
    preview_poster: "/projects/twinAI/preview-poster.jpg",
    preview_video: "/projects/twinAI/preview.mp4",
    services: "AI, Web Development",
    subdesc:
      "**TwinAI** creates virtual representations of patients’ **psychological states**, enabling therapists to **simulate interventions**, track **mood patterns**, and develop **personalized treatment plans**.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "MongoDB",
      "Google Gemini",
      "PyTorch",
    ],
    title: "TwinAI - AI-Powered Digital Twins for Therapy",
    video_overview: "/projects/twinAI/video.mp4",
    year: "2025",
  },
  {
    client: "Personal Project",
    description:
      "A **digital poker chip tracker** that lets you and your friends enjoy **poker games** without **physical chips**.",
    features: [
      "**Real-time chip count** tracking",
      "**Multiple table** support",
      "**Customizable starting** stacks",
      "**Blind timer** and level management",
      "**Game history** and statistics",
    ],
    github: "https://github.com/Benjam11n/Chip",
    hero_image: "/projects/chip/hero.png",
    href: "https://chip-sg.vercel.app/",
    id: "chip",
    location: "Singapore",
    logo: "/projects/chip/logo.png",
    logoStyle: {
      backgroundColor: "#000000",
      border: "0.2px solid #24020b",
      boxShadow: "0px 0px 60px 0px #380310",
    },
    preview_poster: "/projects/chip/preview-poster.jpg",
    preview_video: "/projects/chip/preview.mp4",
    services: "Web App, Real-time",
    status: "completed",
    subdesc:
      "Built with **Next.js, React, TypeScript**, and **Supabase**. **Chip** provides a **seamless** and **reliable** poker experience with **real-time updates** and **easy chip management**.",
    techStack: [
      "Next.js",
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "Framer",
      "Supabase",
    ],
    title: "Chip - Play poker anytime, anywhere",
    video_overview: "/projects/chip/video.mp4",
    year: "2024",
  },
  {
    client: "WorldQuant",
    description:
      "Achieved **4th place** in the prestigious **WorldQuant NUS Alphathon** by developing **alpha-generating quantitative trading strategies**.",
    hero_image: "/projects/worldquant/hero.png",
    id: "worldquant",
    location: "Singapore",
    logo: "/projects/worldquant/logo.png",
    logoStyle: {
      backgroundColor: "#0E1F38",
      border: "0.2px solid #0E2D58",
      boxShadow: "0px 0px 60px 0px #2F67B64D",
    },
    preview_poster: "/projects/worldquant/preview-poster.jpg",
    preview_video: "/projects/worldquant/preview.mp4",
    services: "Quantitative Research, Alpha Design",
    subdesc:
      "Utilized **Fast Expression Language** and **quantitative research methodologies** to identify **market patterns** and develop **high-performance predictive models** on the **BRAIN platform**.",
    techStack: [],
    title: "WorldQuant NUS Alphathon - 4th Place Winner",
    video_overview: "/projects/worldquant/video.mp4",
    year: "2024",
  },
  {
    client: "Personal Project",
    description:
      "**Birds of a Feather** is a **community forum** designed for **bird lovers** to connect, share knowledge, and discuss their passion.",
    features: [
      "**Real-time community** discussions",
      "**Photo and video** sharing",
      "**Group creation** and management",
      "**User profiles** and history",
      "**Bird species identification**",
    ],
    github: "https://github.com/Benjam11n/Birds-of-a-Feather-frontend",
    hero_image: "/projects/birds-of-a-feather/hero.png",
    id: "birds-of-a-feather",
    location: "Singapore",
    logo: "/projects/birds-of-a-feather/logo.avif",
    logoStyle: {
      backgroundColor: "#16015c",
      border: "0.2px solid #0c0036",
      boxShadow: "0px 0px 60px 0px #2F6DB54D",
    },
    preview_poster: "/projects/birds-of-a-feather/preview-poster.jpg",
    preview_video: "/projects/birds-of-a-feather/preview.mp4",
    services: "Community, Forum",
    subdesc:
      "Built with **React, TypeScript, Tailwind CSS, shadcn/ui**, and **Docker**. **Birds of a Feather** is a **modern forum** that brings **bird enthusiasts** together.",
    techStack: [
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "Postgres",
      "Docker",
    ],
    title: "Birds of a Feather - My First React Project",
    video_overview: "/projects/birds-of-a-feather/video.mp4",
    year: "2024",
  },
];

const validatedProjects = projectsArraySchema.parse(rawProjects);

export const PROJECTS: Project[] = validatedProjects;
