import { CheckCircle2 } from "lucide-react";
import type { Project } from "@/lib/types";

export const DEFAULT_FEATURE_ICON = CheckCircle2;

export const PROJECTS: Record<string, Project> = {
  disknee: {
    id: "disknee",
    title:
      "DisKnee - Advanced Computer Vision Platform for Sports Medicine & Rehabilitation",
    description:
      "Pioneering a tele-rehabilitation platform that combines real-time computer vision with biomechanical analysis.",
    subdesc:
      "DisKnee revolutionizes knee recovery by delivering precise movement tracking and instant feedback without expensive hardware. Built with a high-performance WebSocket infrastructure handling 30fps video streams, integrated Google MediaPipe with custom pose smoothing algorithms achieving 99.8% pose detection accuracy.",
    year: "2025",
    client: "Hackathon",
    services: "Computer Vision, Healthcare Tech",
    location: "Singapore",
    hero_image: "/projects/disknee/hero.png",
    logo: "/projects/disknee/logo.png",
    logoStyle: {
      backgroundColor: "#0a1628",
      border: "0.2px solid #1e3a5f",
      boxShadow: "0px 0px 60px 0px #2563eb4D",
    },
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind",
      "Python",
      "PyTorch",
      "FastAPI",
      "WebSocket",
      "MediaPipe",
      "Supabase",
    ],
    features: [
      "Real-time pose detection with 99.8% accuracy",
      "High-performance WebSocket infrastructure for 30fps video streams",
      "Custom pose smoothing algorithms for biomechanical analysis",
      "Microservices architecture separating ML inference from client experience",
      "State management engine for complex rehabilitation metrics tracking",
      "Gamified recovery process with progress visualization",
    ],
  },
  twinAI: {
    id: "twinAI",
    title: "TwinAI - AI-Powered Digital Twins for Therapy",
    description:
      "A platform that uses AI-powered digital twins to revolutionize mental health therapy and treatment.",
    subdesc:
      "TwinAI creates virtual representations of patients’ psychological states, enabling therapists to simulate interventions, track mood patterns, and develop personalized treatment plans.",
    year: "2025",
    client: "Hackathon",
    services: "AI, Web Development",
    location: "Singapore",
    // href: "https://twin-ai-one.vercel.app/",
    github: "https://github.com/Benjam11n/TwinAI",
    video_overview: "/projects/twinAI/video.mp4",
    hero_image: "/projects/twinAI/hero.png",
    logo: "/projects/twinAI/logo.png",
    logoStyle: {
      backgroundColor: "#151a11",
      border: "0.2px solid #233814",
      boxShadow: "0px 0px 60px 0px #324d1f",
    },
    techStack: [
      "Next.js",
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "MongoDB",
      "Google Gemini",
      "PyTorch",
    ],
    features: [
      "Real-time voice-based therapy sessions",
      "Interactive AI patient simulations",
      "Contextual, condition-specific responses",
      "Learning from therapeutic techniques",
      "Voice processing for seamless interaction",
    ],
  },
  quickie: {
    id: "quickie",
    title: "Quickie - AI-Powered Marketplace",
    description:
      "Quickie is an innovative e-commerce platform that leverages AI technology to provide personalized perfume recommendations to users.",
    subdesc:
      "Built as a unique e-commerce app with Next.js 15, Tailwind CSS, TypeScript, Framer Motion, shadcn/ui, Zustand, React Query and MongoDB, Quickie is designed to be beautiful and memorable yet performant.",
    year: "2024",
    client: "Personal Project",
    services: "E-commerce, AI",
    location: "Singapore",
    status: "in-development",
    github: "https://github.com/Benjam11n/Quickie",
    video_overview: "/projects/quickie/video.mp4",
    hero_image: "/projects/quickie/hero.png",
    logo: "/projects/quickie/logo.png",
    logoStyle: {
      backgroundColor: "#170040",
      border: "0.2px solid #0f0226",
      boxShadow: "0px 0px 60px 0px #4f248f",
    },
    techStack: [
      "Next.js",
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "Framer",
      "Zustand",
      "MongoDB",
    ],
    features: [
      "Product search and filtering",
      "AI-powered recommendation system",
      "Waitlist system",
      "User authentication and profiles",
      "Email confirmation and notifications",
    ],
  },
  chip: {
    id: "chip",
    title: "Chip - Play poker anytime, anywhere",
    description:
      "A digital poker chip tracker that lets you and your friends enjoy poker games without physical chips. Perfect for casual games anywhere.",
    subdesc:
      "Built with Next.js, React, TypeScript, Framer motion, TailwindCSS and Supabase, Chip provides a seamless and reliable poker experience with real-time updates and easy chip management.",
    year: "2024",
    client: "Personal Project",
    services: "Web App, Real-time",
    location: "Singapore",
    href: "https://chip-sg.vercel.app/",
    status: "completed",
    github: "https://github.com/Benjam11n/Chip",
    video_overview: "/projects/chip/video.mp4",
    hero_image: "/projects/chip/hero.png",
    logo: "/projects/chip/logo.png",
    logoStyle: {
      backgroundColor: "#000000",
      border: "0.2px solid #24020b",
      boxShadow: "0px 0px 60px 0px #380310",
    },
    techStack: [
      "Next.js",
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "Framer",
      "Supabase",
    ],
    features: [
      "Real-time chip count tracking",
      "Multiple table support",
      "Customizable starting stacks",
      "Blind timer and level management",
      "Game history and statistics",
    ],
  },
  worldquant: {
    id: "worldquant",
    title: "WorldQuant NUS Alphathon - 4th Place Winner",
    description:
      "Achieved 4th place in the prestigious WorldQuant NUS Alphathon by developing and optimizing alpha-generating quantitative trading strategies.",
    subdesc:
      "Utilized Fast Expression Language and quantitative research methodologies to identify market patterns and develop high-performance predictive models on the BRAIN platform.",
    year: "2024",
    client: "WorldQuant",
    services: "Quantitative Research, Alpha Design",
    location: "Singapore",
    video_overview: "/projects/worldquant/video.mp4",
    hero_image: "/projects/worldquant/hero.png",
    logo: "/projects/worldquant/logo.png",
    logoStyle: {
      backgroundColor: "#0E1F38",
      border: "0.2px solid #0E2D58",
      boxShadow: "0px 0px 60px 0px #2F67B64D",
    },
    techStack: [],
  },
  "birds-of-a-feather": {
    id: "birds-of-a-feather",
    title: "Birds of a Feather - My First React Project",
    description:
      "Birds of a Feather is a community forum designed for bird lovers to connect, share knowledge, and discuss their passion for birds.",
    subdesc:
      "Built with React, Typescript Tailwind CSS, shadcn/ui, React Query and Docker, Birds of a Feather is a modern forum that brings bird enthusiasts together.",
    year: "2024",
    client: "Personal Project",
    services: "Community, Forum",
    location: "Singapore",
    github: "https://github.com/Benjam11n/Birds-of-a-Feather-frontend",
    video_overview: "/projects/birds-of-a-feather/video.mp4",
    hero_image: "/projects/birds-of-a-feather/hero.png",
    logo: "/projects/birds-of-a-feather/logo.png",
    logoStyle: {
      backgroundColor: "#16015c",
      border: "0.2px solid #0c0036",
      boxShadow: "0px 0px 60px 0px #2F6DB54D",
    },
    techStack: [
      "React",
      "Tailwind",
      "TypeScript",
      "shadcn/ui",
      "PostgreSQL",
      "Docker",
    ],
    features: [
      "Real-time community discussions",
      "Photo and video sharing for bird sightings",
      "Group creation and management",
      "User profiles with bird watching history",
      "Bird species identification assistance",
    ],
  },
};
