import type { Project } from "@/lib/types/index";
import { projectsArraySchema } from "@/lib/validations/constants";

const rawProjects: Project[] = [
  {
    client: "Personal Project",
    description:
      "**Zucchini** is a **local-first desktop habit tracker** built for people who want consistent daily momentum without handing their routines over to a cloud service.",
    features: [
      "**Local-first tracking** with on-device storage",
      "**Fast daily check-ins** for regular routines",
      "**Streaks and freezes** that protect consistency",
      "**Desktop reminders** for low-friction habits",
      "**History and reviews** to spot progress trends",
    ],
    github: "https://github.com/Benjam11n/zucchini",
    hero_image: "/projects/zucchini/hero.png",
    href: "https://zucchini.codedbyben.com/",
    id: "zucchini",
    location: "Singapore",
    logo: "/projects/zucchini/logo.png",
    logoStyle: {
      colorDark: "#284734",
      colorLight: "#d7f7c9",
    },
    preview_poster: "/projects/zucchini/preview-poster.jpg",
    preview_video: "/projects/zucchini/preview.mp4",
    services: "Desktop App, Productivity",
    status: "in-development",
    subdesc:
      "Built with **Electron, React, TypeScript, Drizzle ORM, Vite**, **Framer Motion**, **Tailwind CSS**, and **shadcn/ui**, **Zucchini** focuses on fast daily check-ins, reminder-driven routines, streak protection, and clear weekly review feedback while keeping your data on your own machine.",
    techStack: [
      "electron",
      "react",
      "typescript",
      "drizzle-orm",
      "vite",
      "framer",
      "tailwind",
      "shadcn-ui",
      "zustand",
    ],
    title: "Zucchini - Local-First Habit Tracker",
    video_overview: "/projects/zucchini/video.mp4",
    year: 2026,
  },
  {
    client: "Hackathon",
    description:
      "Pioneering a **tele-rehabilitation platform** that combines **real-time computer vision** with **biomechanical analysis**.",
    features: [
      "**Real-time pose detection** with **extremely high accuracy**",
      "**Low-latency motion analysis** for guided rehab sessions",
      "**Custom pose smoothing** algorithms",
      "**Microservices architecture** for ML inference",
      "**Complex rehabilitation metrics** tracking",
      "**Gamified recovery** visualization",
    ],
    github: "https://github.com/Benjam11n/disknee",
    hero_image: "/projects/disknee/hero.png",
    id: "disknee",
    location: "Singapore",
    logo: "/projects/disknee/logo.png",
    logoStyle: {
      colorDark: "#7ca3c6",
      colorLight: "#e4f3ff",
    },
    preview_poster: "/projects/disknee/preview-poster.jpg",
    preview_video: "/projects/disknee/preview.mp4",
    services: "Computer Vision, Healthcare",
    subdesc:
      "**DisKnee** revolutionizes knee recovery by delivering **precise movement tracking** and instant feedback without expensive hardware. Built with **Next.js, React, TypeScript, Tailwind CSS, shadcn/ui**, and a **FastAPI-backed** inference pipeline, custom pose smoothing, and calibrated rehabilitation metrics, it focused on responsive movement analysis with **extremely high pose detection accuracy**.",
    techStack: [
      "nextjs",
      "react",
      "typescript",
      "tailwind",
      "shadcn-ui",
      "python",
      "pytorch",
      "fastapi",
      "supabase",
    ],
    title:
      "DisKnee - Advanced Computer Vision Platform for Sports Medicine & Rehabilitation",
    video_overview: "/projects/disknee/video.mp4",
    year: 2025,
  },
  {
    client: "Hackathon",
    description:
      "A platform that uses **AI-powered digital twins** to revolutionize **mental health therapy** and treatment.",
    features: [
      "**Real-time voice-based** therapy sessions",
      "**Interactive AI** patient simulations",
      "**Contextual, condition-specific** responses",
      "**Learning** from therapeutic techniques",
      "**Seamless voice processing** interaction",
    ],
    github: "https://github.com/Benjam11n/TwinAI",
    hero_image: "/projects/twinAI/hero.png",
    id: "twinAI",
    location: "Singapore",
    logo: "/projects/twinAI/logo.png",
    logoStyle: {
      colorDark: "#8bad63",
      colorLight: "#edf4de",
    },
    preview_poster: "/projects/twinAI/preview-poster.jpg",
    preview_video: "/projects/twinAI/preview.mp4",
    services: "AI, Web Development",
    subdesc:
      "**TwinAI** creates virtual representations of patients’ **psychological states**, enabling therapists to **simulate interventions**, track **mood patterns**, and develop **personalized treatment plans**.",
    techStack: [
      "nextjs",
      "react",
      "tailwind",
      "typescript",
      "shadcn-ui",
      "mongodb",
      "pytorch",
    ],
    title: "TwinAI - AI-Powered Digital Twins for Therapy",
    video_overview: "/projects/twinAI/video.mp4",
    year: 2025,
  },
  {
    client: "Personal Project",
    description:
      "A **digital poker chip tracker** that lets you and your friends enjoy **poker games** without **physical chips**.",
    features: [
      "**Real-time chip count** tracking",
      "**Multiple table** support",
      "**Customizable starting** stacks",
      "**Blind timer** and level management",
      "**Game history** and statistics",
    ],
    github: "https://github.com/Benjam11n/Chip",
    hero_image: "/projects/chip/hero.png",
    href: "https://chip-sg.vercel.app/",
    id: "chip",
    location: "Singapore",
    logo: "/projects/chip/logo.png",
    logoStyle: {
      colorDark: "#7a213c",
      colorLight: "#ffe5ec",
    },
    preview_poster: "/projects/chip/preview-poster.jpg",
    preview_video: "/projects/chip/preview.mp4",
    services: "Web App, Real-time",
    status: "completed",
    subdesc:
      "Built with **Next.js, React, TypeScript**, and **Supabase**. **Chip** provides a **seamless** and **reliable** poker experience with **real-time updates** and **easy chip management**.",
    techStack: [
      "nextjs",
      "react",
      "tailwind",
      "typescript",
      "shadcn-ui",
      "framer",
      "supabase",
    ],
    title: "Chip - Play poker anytime, anywhere",
    video_overview: "/projects/chip/video.mp4",
    year: 2024,
  },
  {
    client: "WorldQuant",
    description:
      "Achieved **4th place** in the prestigious **WorldQuant NUS Alphathon** by developing **alpha-generating quantitative trading strategies**.",
    hero_image: "/projects/worldquant/hero.png",
    id: "worldquant",
    location: "Singapore",
    logo: "/projects/worldquant/logo.png",
    logoStyle: {
      colorDark: "#7ba6d1",
      colorLight: "#e8f4ff",
    },
    preview_poster: "/projects/worldquant/preview-poster.jpg",
    preview_video: "/projects/worldquant/preview.mp4",
    services: "Quantitative Research, Alpha Design",
    subdesc:
      "Utilized **Fast Expression Language** and **quantitative research methodologies** to identify **market patterns** and develop **high-performance predictive models** on the **BRAIN platform**.",
    techStack: [],
    title: "WorldQuant NUS Alphathon - 4th Place Winner",
    video_overview: "/projects/worldquant/video.mp4",
    year: 2024,
  },
  {
    client: "Personal Project",
    description:
      "**Birds of a Feather** is a **community forum** designed for **bird lovers** to connect, share knowledge, and discuss their passion.",
    features: [
      "**Real-time community** discussions",
      "**Photo and video** sharing",
      "**Group creation** and management",
      "**User profiles** and history",
    ],
    github: "https://github.com/Benjam11n/Birds-of-a-Feather-frontend",
    hero_image: "/projects/birds-of-a-feather/hero.png",
    id: "birds-of-a-feather",
    location: "Singapore",
    logo: "/projects/birds-of-a-feather/logo.avif",
    logoStyle: {
      colorDark: "#7b86b6",
      colorLight: "#fff5dc",
    },
    preview_poster: "/projects/birds-of-a-feather/preview-poster.jpg",
    preview_video: "/projects/birds-of-a-feather/preview.mp4",
    services: "Community, Forum",
    subdesc:
      "Built with **React, TypeScript, Tailwind CSS, shadcn/ui**, and **Docker**. **Birds of a Feather** is a **modern forum** that brings **bird enthusiasts** together.",
    techStack: [
      "react",
      "tailwind",
      "typescript",
      "shadcn-ui",
      "postgres",
      "docker",
    ],
    title: "Birds of a Feather - My First React Project",
    video_overview: "/projects/birds-of-a-feather/video.mp4",
    year: 2024,
  },
];

const validatedProjects = projectsArraySchema.parse(rawProjects);

export const PROJECTS: Project[] = validatedProjects;
