import { ProficiencyLevel, TechCategory } from "@/lib/types";
import type { TechId, TechStack } from "@/lib/types";

const createTechStackItem = ({
  category,
  colorDark,
  colorLight,
  icon,
  id,
  name,
  proficiency,
}: TechStack): TechStack => ({
  category,
  colorDark,
  colorLight,
  icon,
  id,
  name,
  proficiency,
});

export const TECH_STACK: TechStack[] = [
  createTechStackItem({
    category: TechCategory.LANGUAGE,
    colorDark: "#00273F",
    colorLight: "#E3F2FD",
    icon: "/tech-stack/typescript.svg",
    id: "typescript",
    name: "TypeScript",
    proficiency: ProficiencyLevel.EXPERT,
  }),
  createTechStackItem({
    category: TechCategory.LANGUAGE,
    colorDark: "#1E2D3B",
    colorLight: "#E3F2FD",
    icon: "/tech-stack/python.svg",
    id: "python",
    name: "Python",
    proficiency: ProficiencyLevel.EXPERT,
  }),
  createTechStackItem({
    category: TechCategory.LANGUAGE,
    colorDark: "#002c39ff",
    colorLight: "#FBE9E7",
    icon: "/tech-stack/java.svg",
    id: "java",
    name: "Java",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.LANGUAGE,
    colorDark: "#3D3200",
    colorLight: "#FFF8E1",
    icon: "/tech-stack/javascript.svg",
    id: "javascript",
    name: "JavaScript",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.LANGUAGE,
    colorDark: "#d8f7ffff",
    colorLight: "#E0F7FA",
    icon: "/tech-stack/golang.svg",
    id: "golang",
    name: "Golang",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.FRAMEWORK,
    colorDark: "#F3F4F6",
    colorLight: "#F3F4F6",
    icon: "/tech-stack/nextjs.svg",
    id: "nextjs",
    name: "Next.js",
    proficiency: ProficiencyLevel.EXPERT,
  }),
  createTechStackItem({
    category: TechCategory.FRONTEND,
    colorDark: "#001b59",
    colorLight: "#E0F7FA",
    icon: "/tech-stack/react.svg",
    id: "react",
    name: "React",
    proficiency: ProficiencyLevel.EXPERT,
  }),
  createTechStackItem({
    category: TechCategory.STYLING,
    colorDark: "#0B2830",
    colorLight: "#E0F2F1",
    icon: "/tech-stack/tailwindcss.png",
    id: "tailwind",
    name: "Tailwind",
    proficiency: ProficiencyLevel.EXPERT,
  }),
  createTechStackItem({
    category: TechCategory.FRONTEND,
    colorDark: "#0F2F24",
    colorLight: "#E8F5E9",
    icon: "/tech-stack/vue.svg",
    id: "vue",
    name: "Vue",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.DEVOPS,
    colorDark: "#0D2C4A",
    colorLight: "#E1F5FE",
    icon: "/tech-stack/docker.svg",
    id: "docker",
    name: "Docker",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.BACKEND,
    colorDark: "#E3F2FD",
    colorLight: "#E3F2FD",
    icon: "/tech-stack/drizzle.svg",
    id: "drizzle-orm",
    name: "Drizzle ORM",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.FRAMEWORK,
    colorDark: "#f0f0f0",
    colorLight: "#f0f0f0",
    icon: "/tech-stack/electron.svg",
    id: "electron",
    name: "Electron",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.ANIMATION,
    colorDark: "#180036",
    colorLight: "#F3E5F5",
    icon: "/tech-stack/framer.png",
    id: "framer",
    name: "Framer",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.ANIMATION,
    colorDark: "#DFF7A8",
    colorLight: "#F4FFE3",
    icon: "/tech-stack/gsap.svg",
    id: "gsap",
    name: "GSAP",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.BACKEND,
    colorDark: "#E6F8F4",
    colorLight: "#E6F8F4",
    icon: "/tech-stack/fastapi.svg",
    id: "fastapi",
    name: "FastAPI",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.FRONTEND,
    colorDark: "#E2E8F0",
    colorLight: "#F8FAFC",
    icon: "/tech-stack/shadcn-ui.svg",
    id: "shadcn-ui",
    name: "shadcn/ui",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.FRAMEWORK,
    colorDark: "#231A45",
    colorLight: "#EEF2FF",
    icon: "/tech-stack/vite.svg",
    id: "vite",
    name: "Vite",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.BACKEND,
    colorDark: "#518742ff",
    colorLight: "#F1F8E9",
    icon: "/tech-stack/node.svg",
    id: "nodejs",
    name: "Node.js",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.AI_ML,
    colorDark: "#64271bff",
    colorLight: "#FFF3E0",
    icon: "/tech-stack/pytorch.svg",
    id: "pytorch",
    name: "PyTorch",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.AI_ML,
    colorDark: "#013243",
    colorLight: "#E1F5FE",
    icon: "/tech-stack/numpy.svg",
    id: "numpy",
    name: "Numpy",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.AI_ML,
    colorDark: "#5533ddff",
    colorLight: "#F3E5F5",
    icon: "/tech-stack/pandas.svg",
    id: "pandas",
    name: "Pandas",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.AI_ML,
    colorDark: "#FF6F00",
    colorLight: "#FFF3E0",
    icon: "/tech-stack/tensorflow.svg",
    id: "tensorflow",
    name: "Tensorflow",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.DATABASE,
    colorDark: "#001E0E",
    colorLight: "#E8F5E9",
    icon: "/tech-stack/mongodb.svg",
    id: "mongodb",
    name: "MongoDB",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
  createTechStackItem({
    category: TechCategory.DATABASE,
    colorDark: "#0E1A2B",
    colorLight: "#E3F2FD",
    icon: "/tech-stack/pgsql.svg",
    id: "postgres",
    name: "Postgres",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.DATABASE,
    colorDark: "#146541ff",
    colorLight: "#E8F5E9",
    icon: "/tech-stack/supabase.svg",
    id: "supabase",
    name: "Supabase",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.FRONTEND,
    colorDark: "#FF4154",
    colorLight: "#FFF1F2",
    icon: "/tech-stack/react-query.svg",
    id: "react-query",
    name: "React Query",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.FRONTEND,
    colorDark: "#6f675fff",
    colorLight: "#FFFDE7",
    icon: "/tech-stack/zustand.png",
    id: "zustand",
    name: "Zustand",
    proficiency: ProficiencyLevel.ADVANCED,
  }),
  createTechStackItem({
    category: TechCategory.MOBILE,
    colorDark: "#122f60ff",
    colorLight: "#E1F5FE",
    icon: "/tech-stack/ionic.svg",
    id: "ionic",
    name: "Ionic",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  }),
];

const techStackEntries = TECH_STACK.map((tech) => [tech.id, tech] as const);

export const TECH_STACK_BY_ID = Object.fromEntries(techStackEntries) as Record<
  TechId,
  TechStack
>;
