import { ProficiencyLevel, TechCategory } from "@/lib/types";

export const TECH_STACK = [
  // --- Languages ---
  {
    name: "TypeScript",
    icon: "/assets/typescript.svg",
    category: TechCategory.LANGUAGE,
    colorLight: "#E3F2FD",
    colorDark: "#00273F",
    proficiency: ProficiencyLevel.EXPERT,
  },
  {
    name: "Python",
    icon: "/assets/python.svg",
    category: TechCategory.LANGUAGE,
    colorLight: "#E3F2FD",
    colorDark: "#1E2D3B",
    proficiency: ProficiencyLevel.EXPERT,
  },
  {
    name: "Java",
    icon: "/assets/java.svg",
    category: TechCategory.LANGUAGE,
    colorLight: "#FBE9E7",
    colorDark: "#002c39ff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "Golang",
    icon: "/assets/golang.svg",
    category: TechCategory.LANGUAGE,
    colorLight: "#E0F7FA",
    colorDark: "#d8f7ffff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },

  // --- AI/ML ---
  {
    name: "Numpy",
    icon: "/assets/numpy.svg",
    category: TechCategory.AI_ML,
    colorLight: "#E1F5FE",
    colorDark: "#013243",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "Pandas",
    icon: "/assets/pandas.svg",
    category: TechCategory.AI_ML,
    colorLight: "#F3E5F5",
    colorDark: "#5533ddff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "PyTorch",
    icon: "/assets/pytorch.svg",
    category: TechCategory.AI_ML,
    colorLight: "#FFF3E0",
    colorDark: "#64271bff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "Tensorflow",
    icon: "/assets/tensorflow.svg",
    category: TechCategory.AI_ML,
    colorLight: "#FFF3E0",
    colorDark: "#FF6F00",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },

  // --- Web Development ---
  {
    name: "Electron",
    icon: "/assets/electron.svg",
    category: TechCategory.FRAMEWORK,
    colorLight: "#E8FFF8",
    colorDark: "#3dae91",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "Framer Motion",
    icon: "/assets/framer.png",
    category: TechCategory.ANIMATION,
    colorLight: "#F3E5F5",
    colorDark: "#180036",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "GSAP",
    icon: "/assets/gsap.svg",
    category: TechCategory.ANIMATION,
    colorLight: "#F4FFE3",
    colorDark: "#DFF7A8",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "Ionic",
    icon: "/assets/ionic.svg",
    category: TechCategory.MOBILE,
    colorLight: "#E1F5FE",
    colorDark: "#122f60ff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
  {
    name: "Next.js",
    icon: "/assets/nextjs.svg",
    category: TechCategory.FRAMEWORK,
    colorLight: "#F3F4F6",
    colorDark: "#F3F4F6",
    proficiency: ProficiencyLevel.EXPERT,
  },
  {
    name: "Node.js",
    icon: "/assets/node.svg",
    category: TechCategory.BACKEND,
    colorLight: "#F1F8E9",
    colorDark: "#518742ff",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "React",
    icon: "/assets/react.svg",
    category: TechCategory.FRONTEND,
    colorLight: "#E0F7FA",
    colorDark: "#001b59",
    proficiency: ProficiencyLevel.EXPERT,
  },
  {
    name: "React Query",
    icon: "/assets/react-query.svg",
    category: TechCategory.FRONTEND,
    colorLight: "#FFF1F2",
    colorDark: "#FF4154",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "Tailwind",
    icon: "/assets/tailwindcss.png",
    category: TechCategory.STYLING,
    colorLight: "#E0F2F1",
    colorDark: "#0B2830",
    proficiency: ProficiencyLevel.EXPERT,
  },
  {
    name: "Zustand",
    icon: "/assets/zustand.png",
    category: TechCategory.FRONTEND,
    colorLight: "#FFFDE7",
    colorDark: "#6f675fff",
    proficiency: ProficiencyLevel.ADVANCED,
  },

  // --- Databases & DevOps ---
  {
    name: "Docker",
    icon: "/assets/docker.svg",
    category: TechCategory.DEVOPS,
    colorLight: "#E1F5FE",
    colorDark: "#0D2C4A",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "MongoDB",
    icon: "/assets/mongodb.svg",
    category: TechCategory.DATABASE,
    colorLight: "#E8F5E9",
    colorDark: "#001E0E",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "Postgres",
    icon: "/assets/pgsql.svg",
    category: TechCategory.DATABASE,
    colorLight: "#E3F2FD",
    colorDark: "#0E1A2B",
    proficiency: ProficiencyLevel.ADVANCED,
  },
  {
    name: "Supabase",
    icon: "/assets/supabase.svg",
    category: TechCategory.DATABASE,
    colorLight: "#E8F5E9",
    colorDark: "#146541ff",
    proficiency: ProficiencyLevel.INTERMEDIATE,
  },
];
